<?php

/**
 * Implements hook_form_FORM_ID_alter();
 */
function atwork_group_wizard_form_section_node_form_alter(&$form, &$form_state, $form_id) {
  drupal_add_css('.field-indent-1 {padding-left: 1em;} .field-indent-2 {padding-left: 2em;}', $option['type'] = 'inline');
  // Hide link for weighting images (we only have one)
  drupal_add_css(".tabledrag-toggle-weight { display: none; } .handle {display: none; }", $option['type'] = 'inline');
  //dpm(arg());
  //dpm($form);
  // set title from Create Group to Create a Group
  if (arg(0) == 'node' && arg(2) == 'section') {
    drupal_set_title(t('Create a Group'));
  }


  // only allow 1 image
  if ($form_id == 'section_node_form') {
    if (isset($form['field_image'][$form['field_image']['#language']][1])) {
      $form['field_image'][$form['field_image']['#language']][1]['#access'] = FALSE;
    }
  }

  // Alter the title
  $form['field_image']['und']['#file_upload_title'] = 'Image';
  // Hide box title
  $form['field_image']['und']['#title'] = '';


  // attach needed js files
  $form['#attached']['js'][drupal_get_path('module', 'atwork_group_wizard') . '/atwork_group_wizard.js'] = array(
    'type' => 'file',
  );
  $form['#attached']['library'][] = array('system', 'ui.sortable');



  $form['field_grp_opt_blog_sidebar']['#attributes']['class'][] = 'field-indent-1';
  $form['field_grp_opt_event_sidebar']['#attributes']['class'][] = 'field-indent-1';
  $form['field_grp_opt_event_sidebar_cal']['#attributes']['class'][] = 'field-indent-2';
  $form['field_grp_opt_qa_sidebar']['#attributes']['class'][] = 'field-indent-1';
  $form['field_grp_opt_poll_sidebar']['#attributes']['class'][] = 'field-indent-1';
  $form['field_grp_opt_issue_sidebar']['#attributes']['class'][] = 'field-indent-1';
  $form['field_grp_opt_gallery_sidebar']['#attributes']['class'][] = 'field-indent-1';


  $form['og_menu']['#title'] = t('Enable Group Menu');
  //$form['og_menu']['#default_value'] = TRUE;
  //$form['og_menu']['#access'] = FALSE;

  $form['field_grp_opt_block_order']['#attributes']['style'][] = 'display: none;';

  // get existing data
  $blocks = explode('|', $form['field_grp_opt_block_order'][$form['field_grp_opt_block_order']['#language']][0]['#default_value']);

  $items = array();

  foreach ($blocks as $block) {
    $items[] = $block;
  }

  $variables = array(
    'title' => t('Sidebar Block Order'),
    'items' => $items,
    'type' => 'ul',
    'attributes' => array(
      'class' => array('sortable'),
    ),
  );

  $form['field_grp_opt_block_order']['#prefix'] = theme('item_list', $variables);

  //hiding block stuff for non-admins
  if (!_atwork_is_admin()) {
    field_group_hide_field_groups($form, array('group_block_options', 'group_advanced'));
  }

  $form['#validate'][] = 'atwork_group_wizard_validate';


  if(isset($form['field_grp_opt_blog']['#attributes']['data-tooltip'])) {
    $form['field_grp_opt_blog']['#attributes']['data-tooltip'][] .= _atwork_instructions('atwork_instructions_blog');
  } else {
    $form['field_grp_opt_blog']['#attributes']['data-tooltip'] = array(_atwork_instructions('atwork_instructions_blog'));
  }
  $form['field_grp_opt_blog']['#attributes']['class'][] = 'atwork-instuction';
  $form['field_grp_opt_blog'][$form['field_grp_opt_blog']['#language']]['#title'] .= ' ' . _atwork_fa('info-circle');

  if(isset($form['field_grp_opt_event']['#attributes']['data-tooltip'])) {
      $form['field_grp_opt_event']['#attributes']['data-tooltip'][] .= _atwork_instructions('atwork_instructions_event');
  } else {
    $form['field_grp_opt_event']['#attributes']['data-tooltip'] = array(_atwork_instructions('atwork_instructions_event'));
  }
  $form['field_grp_opt_event']['#attributes']['class'][] = 'atwork-instuction';
  $form['field_grp_opt_event'][$form['field_grp_opt_event']['#language']]['#title'] .= ' ' . _atwork_fa('info-circle');

  // if(isset($form['field_opt_grp_status_update']['#attributes']['data-tooltip'])) {
  //     $form['field_opt_grp_status_update']['#attributes']['data-tooltip'][] .= _atwork_instructions('atwork_instructions_status_update');
  // } else {
  //   $form['field_opt_grp_status_update']['#attributes']['data-tooltip'] = array(_atwork_instructions('atwork_instructions_status_update'));
  // }
  // $form['field_opt_grp_status_update']['#attributes']['class'][] = 'atwork-instruction';
  // $form['field_opt_grp_status_update'][$form['field_opt_grp_status_update']['#language']]['#title'] .= ' ' . _atwork_fa('info-circle');

  // Status update no longer used, so lets hide it for now
  $form['field_opt_grp_status_update']['#access'] = FALSE;

  if(isset($form['field_grp_opt_qa']['#attributes']['data-tooltip'])) {
      $form['field_grp_opt_qa']['#attributes']['data-tooltip'][] .= _atwork_instructions('atwork_instructions_qa');
  } else {
    $form['field_grp_opt_qa']['#attributes']['data-tooltip'] = array(_atwork_instructions('atwork_instructions_qa'));
  }
  $form['field_grp_opt_qa']['#attributes']['class'][] = 'atwork-instuction';
  $form['field_grp_opt_qa'][$form['field_grp_opt_qa']['#language']]['#title'] .= ' ' . _atwork_fa('info-circle');

  //if(isset($form['field_grp_opt_issue']['#attributes']['data-tooltip'])) {
  //    $form['field_grp_opt_issue']['#attributes']['data-tooltip'][] .= _atwork_instructions('atwork_instructions_task_list');
  //} else {
  //  $form['field_grp_opt_issue']['#attributes']['data-tooltip'] = array(_atwork_instructions('atwork_instructions_task_list'));
  //}
  //$form['field_grp_opt_issue']['#attributes']['class'][] = 'atwork-instuction';
  //$form['field_grp_opt_issue'][$form['field_grp_opt_issue']['#language']]['#title'] .= ' ' . _atwork_fa('info-circle');

  // Task Management is no longer part of groups, lets hide it
  $form['field_grp_opt_issue']['#access'] = FALSE;

  if(isset($form['field_grp_opt_page']['#attributes']['data-tooltip'])) {
      $form['field_grp_opt_page']['#attributes']['data-tooltip'][] .= _atwork_instructions('atwork_instructions_group_page');
  } else {
    $form['field_grp_opt_page']['#attributes']['data-tooltip'] = array(_atwork_instructions('atwork_instructions_group_page'));
  }
  $form['field_grp_opt_page']['#attributes']['class'][] = 'atwork-instuction';
  $form['field_grp_opt_page'][$form['field_grp_opt_page']['#language']]['#title'] .= ' ' . _atwork_fa('info-circle');

  if(isset($form['field_grp_opt_gallery']['#attributes']['data-tooltip'])) {
      $form['field_grp_opt_gallery']['#attributes']['data-tooltip'][] .= _atwork_instructions('atwork_instructions_gallery');
  } else {
    $form['field_grp_opt_gallery']['#attributes']['data-tooltip'] = array(_atwork_instructions('atwork_instructions_gallery'));
  }
  $form['field_grp_opt_gallery']['#attributes']['class'][] = 'atwork-instuction';
  $form['field_grp_opt_gallery'][$form['field_grp_opt_gallery']['#language']]['#title'] .= ' ' . _atwork_fa('info-circle');

  // if(isset($form['field_grp_opt_file']['#attributes']['data-tooltip'])) {
  //     $form['field_grp_opt_file']['#attributes']['data-tooltip'][] .= _atwork_instructions('atwork_instructions_document');
  // } else {
  //   $form['field_grp_opt_file']['#attributes']['data-tooltip'] = array(_atwork_instructions('atwork_instructions_document'));
  //}
  //$form['field_grp_opt_file']['#attributes']['class'][] = 'atwork-instuction';
  //$form['field_grp_opt_file'][$form['field_grp_opt_file']['#language']]['#title'] .= ' ' . _atwork_fa('info-circle');

  // File Management is no longer part of groups, lets hide it.
  $form['field_grp_opt_file']['#access'] = FALSE;

  if(isset($form['field_grp_opt_poll']['#attributes']['data-tooltip'])) {
      $form['field_grp_opt_poll']['#attributes']['data-tooltip'][] .= _atwork_instructions('atwork_instructions_poll');
  } else {
    $form['field_grp_opt_poll']['#attributes']['data-tooltip'] = array(_atwork_instructions('atwork_instructions_poll'));
  }
  $form['field_grp_opt_poll']['#attributes']['class'][] = 'atwork-instuction';
  $form['field_grp_opt_poll'][$form['field_grp_opt_poll']['#language']]['#title'] .= ' ' . _atwork_fa('info-circle');

  if(isset($form['field_grp_opt_news']['#attributes']['data-tooltip'])) {
      $form['field_grp_opt_news']['#attributes']['data-tooltip'][] .= _atwork_instructions('atwork_instructions_article');
  } else {
    $form['field_grp_opt_news']['#attributes']['data-tooltip'] = array(_atwork_instructions('atwork_instructions_article'));
  }
  $form['field_grp_opt_news']['#attributes']['class'][] = 'atwork-instuction';
  $form['field_grp_opt_news'][$form['field_grp_opt_news']['#language']]['#title'] .= ' ' . _atwork_fa('info-circle');

  //dpm($form);

 // dpm($form_state['values']);
}

function atwork_group_wizard_validate(&$form, &$form_state) {
  // Tweak our required field error messages for more clarity
  if(form_get_errors()) {

    if(in_array('Title field is required.', $_SESSION['messages']['error'])){
      $i = array_search('Title field is required.', $_SESSION['messages']['error']);
      $title_error = $_SESSION['messages']['error'][$i];
    }

    if(in_array('Tags field is required.', $_SESSION['messages']['error'])){
      $tag_error = "Please add tag(s) to help promote your content in related topics.";
    }

    if(in_array(' field is required.', $_SESSION['messages']['error'])){
      $i = array_search(' field is required.', $_SESSION['messages']['error']);
      $image_error = 'Image ' . $_SESSION['messages']['error'][$i];
    }

    if(in_array('Group Description field is required.', $_SESSION['messages']['error'])) {
      $i = array_search('Group Description field is required.', $_SESSION['messages']['error']);
      $group_description_error = $_SESSION['messages']['error'][$i];
    }

    if(in_array('You must agree to the terms.', $_SESSION['messages']['error'])){
      $i = array_search('You must agree to the terms.', $_SESSION['messages']['error']);
      $accept_terms_error = $_SESSION['messages']['error'][$i];
    }

    // Empty array so we can reorder to match page order
    unset($_SESSION['messages']['error']);
    $_SESSION['messages']['error'] = array();

    $j = 0;

    if (isset($title_error)){
      $_SESSION['messages']['error'][$j] = $title_error;
      $j++;
    }
    if(isset($image_error)) {
     $_SESSION['messages']['error'][$j] = $image_error;
      $j++;
    }
    if(isset($group_description_error)){
      $_SESSION['messages']['error'][$j] = $group_description_error;
      $j++;
    }
    if(isset($tag_error)){
      $_SESSION['messages']['error'][$j] = $tag_error;
      $j++;
    }
    if(isset($accept_terms_error)){
      $_SESSION['messages']['error'][$j] = $accept_terms_error;
      $j++;
    }
    //dpm($_SESSION['messages']['error']);
  }


  if (!form_get_errors()) {
    // check if title exists in a group that is not created yet
    if (!isset($form_state['node']->nid)){
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'section')
        //->propertyCondition('nid', $form_state['node']->nid, '!=')
        ->propertyCondition('title', $form_state['values']['title']);

      $result = $query->execute();
      //dpm($result);
    }
    // check if title exists in a group that is currently being edited (changing title)
    if (isset($form_state['node']->nid)){
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'section')
        ->propertyCondition('nid', $form_state['node']->nid, '!=')
        ->propertyCondition('title', $form_state['values']['title']);

      $result = $query->execute();
      //dpm($result);
    }
    if (isset($result['node'])) {
      form_set_error('title', t('A group with this name already exists, please choose a different group title and click the <strong>save</strong> button'));
    }
  }
}
