<?php
// $Id$

/**
 * @file
 */


/**
* Implementation of hook_init()
 *
 * Add our needed js file
*/
function presence_init() {
  drupal_add_js(drupal_get_path('module', 'presence').'/jellybean/init.js');
}

/**
 * Just give me the presence icon!
 */
function _presence_jellybean($email) {
  $output = '<span class="presence_stay"><img src="/'
              . drupal_get_path('module', 'presence') . '/jellybean/ocs_images/blank.gif" id="'
              . md5(uniqid(rand(), true)). '" border="0" class="jellybean" height="10" width="10" onload="IMNRC(\''
              . $email . '\');" ShowOfflinePawn=1 /></span>';
  return $output;
}

/*
 * Implementation of hook_theme_registry_alter()
 *
 * Register our presence_username() theme function
 */
function presence_theme_registry_alter(&$theme_registry) {
  $theme_registry['username']['theme path'] = drupal_get_path('module', 'presence');
  $theme_registry['username']['function'] = 'presence_username';
}

/*
 * Implementation of theme_username()
 *
 * Add our fancy jellybean
 */
function presence_username($variables) {
  //dpm($variables);

  // drupal core truncates name
  if (isset($variables['name_raw']) && $variables['name_raw']) {
    $variables['name'] = check_plain($variables['name_raw']);
  }

  if (isset($variables['new_window']) && $variables['new_window']) {
    $variables['link_options']['attributes']['onclick'] = 'window.open(this.href); return false;';
  }

  if ($variables['uid']) {
    $user = user_load($variables['uid']);
    if (!$user) {
      return $variables['name'];
    }

    $profile_enabled = FALSE;
    $executive = FALSE;

    if (isset($user->roles[10])) {
      $executive = TRUE;
      //dpm('exec');
    }

    $items = field_get_items('user', $user, 'field_display_name', $user->language);
    $public_profile = field_get_items('user', $user, 'field_public_profile', $user->language);

    // temp for prototype
    $public_profile[0]['value'] = 1;
    $executive = TRUE;

    if (isset($public_profile[0]['value']) && $public_profile[0]['value']) {
      $profile_enabled = TRUE;
    }

    if (isset($items[0]['value'])) {
      $variables['name'] = $items[0]['value'];
      $add_presence = TRUE;
    }

    if (isset($variables['link_path']) && (($executive && $profile_enabled) || user_access('administer users'))) {
      if (isset($variables['email_link']) && $variables['email_link']) {
        $variables['link_path'] = 'mailto:' . $user->mail;
        $variables['link_options']['absolute'] = TRUE;
      }
      // We have a link path, so we should generate a link using l().
      // Additional classes may be added as array elements like
      // $variables['link_options']['attributes']['class'][] = 'myclass';
     //dpm($variables);
      $output = l($variables['name'] . $variables['extra'], $variables['link_path'], $variables['link_options']);
    }
    elseif ((($executive && $profile_enabled) || user_access('administer users'))) {
      $output = l($variables['name'] . $variables['extra'], 'user/' . $variables['uid'], $variables['link_options']);
    }
    else {
      // Modules may have added important attributes so they must be included
      // in the output. Additional classes may be added as array elements like
      // $variables['attributes_array']['class'][] = 'myclass';
      $output = '<span' . drupal_attributes($variables['attributes_array']) . '>' . $variables['name'] . $variables['extra'] . '</span>';
    }

    if (isset($add_presence)) {
      //$output = _presence_jellybean($user->mail) . $output;
    }
  }
  else {
    return $variables['name'];
  }

  return $output;
}
