<?php

// Demo app from https://www.alloymagnetic.com/blog/192/angular-2-boilerplate-setup-small-drupal-7-applications
function atwork_premiers_awards_angular_menu() {
  $items = [];
  $items['angular2'] = [
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,    
    'access arguments' => array('access content'),
    'page callback' => 'angular_demo_callback',
  ];
  return $items;
}

function angular_demo_callback() {
  $build['content'] = [
    '#theme' => [
      'atwork_premiers_awards_angular_component',
    ],
    '#attached' => [
      'js' => [
        libraries_get_path('node_modules') . '/core-js/client/shim.min.js',
        libraries_get_path('node_modules') . '/zone.js/dist/zone.js',
        libraries_get_path('node_modules') . '/reflect-metadata/Reflect.js',
        libraries_get_path('node_modules') . '/rxjs/bundles/Rx.js',
        libraries_get_path('node_modules') . '/@angular/core/bundles/core.umd.js',
        libraries_get_path('node_modules') . '/@angular/forms/bundles/forms.umd.js', 
        libraries_get_path('node_modules') . '/@angular/http/bundles/http.umd.js',
        libraries_get_path('node_modules') . '/@angular/common/bundles/common.umd.js',
        libraries_get_path('node_modules') . '/@angular/compiler/bundles/compiler.umd.js',
        libraries_get_path('node_modules') . '/@angular/platform-browser/bundles/platform-browser.umd.js',
        libraries_get_path('node_modules') . '/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
        drupal_get_path('module', 'atwork_premiers_awards_angular') . '/js/atwork_premiers_awards_angular.component.js',
        drupal_get_path('module', 'atwork_premiers_awards_angular') . '/js/atwork_premiers_awards_angular.module.js',
        drupal_get_path('module', 'atwork_premiers_awards_angular') . '/js/atwork_premiers_awards_angular.main.js',
      ],
      'ts' => [
        drupal_get_path('module', 'atwork_premiers_awards_angular') . '/js/atwork_premiers_awards_angular.component.js',
      ],
    ],
  ];
  return $build;
}

function atwork_premiers_awards_angular_theme($existing, $type, $theme, $path) {
  // TODO: Pass $user to the theme
  // TODO: Check if user has previously filled out an application
  global $user;
  $current_user = user_load($user->uid);
  $previous_reg = get_registration_number($current_user);
  return [
    'atwork_premiers_awards_angular_component' => [
      'template' => 'atwork-premiers-awards-angular-component',
      'variables' => array(
        'user'=>$current_user,
        'previous_reg'=>$previous_reg,
      ),
      'path' => drupal_get_path('module', 'atwork_premiers_awards_angular') . '/theme',
    ],
  ];
}

function get_registration_number($current_user){
  //TODO: Look in DB and find out if user has registered yet, and how many people they registered
  // return an array of these properties, or a false.
  return true;
}