  /**
 * JS function for LSA ministry key array
 * Drupal.jquery
 * Written by Thayne Werdal March 2016
 */

  function ministry_list_complete() {
    ministry_list = {
      17:"Agricultural Land Commission",
      19:"BC Arts Council",
      20:"BC Farm Industry Review Board",
      21:"BC Human Rights Tribunal",
      22:"BC Pension Corporation",
      23:"BC Public Service Agency",
      24:"BC Review Board",
      89:"BC Transportation Financing Authority",
      25:"Board Resourcing and Development Office",
      89:"Civil Resolution Tribunal",
      85:"Community Care and Assisted Living Appeal Board",
      28:"Community Living BC",
      31:"Crown Agencies Resource Office",
      32:"Destination BC",
      34:"Elections BC",
      86:"Employment and Assistance Appeal Tribunal",
      37:"Environmental Appeal Board",
      38:"Environmental Assessment Office",
      40:"Financial Institutions Commission",
      41:"Financial Services Tribunal",
      42:"Forest Appeals Commission",
      43:"Forest Practices Board",
      47:"Government Communications and Public Engagement",
      87:"Hospital Appeal Board",
      49:"Independent Investigations Office",
      50:"Intergovernmental Relations Secretariat",
      52:"Islands Trust",
      57:"Legislative Assembly of BC",
      58:"Liquor Distribution Branch",
      15:"Ministry of Aboriginal Relations and Reconciliation",
      16:"Ministry of Advanced Education",
      18:"Ministry of Agriculture",
      26:"Ministry of Children and Family Development",
      27:"",
      29:"Ministry of Community, Sport and Cultural Development",
      33:"Ministry of Education",
      35:"Ministry of Energy and Mines",
      36:"Ministry of Environment",
      39:"Ministry of Finance",
      44:"Ministry of Forests, Lands and Natural Resource Operations",
      45:"",
      46:"",
      48:"Ministry of Health",
      51:"Ministry of International Trade",
      53:"Ministry of Jobs, Tourism and Skills Training",
      54:"Ministry of Justice",
      55:"",
      60:"Ministry of Natural Gas Development",
      74:"Ministry of Public Safety and Solicitor General",
      79:"Ministry of Small Business and Red Tape Reduction",
      80:"Ministry of Social Development and Social Innovation",
      81:"Ministry of Technology, Innovation and Citizens' Services",
      82:"Ministry of Transportation and Infrastructure",
      61:"Office of the Auditor General",
      62:"Office of the Auditor General for Local Government",
      63:"Office of the Fire Commissioner",
      64:"Office of the Information and Privacy Commissioner",
      65:"Office of the Merit Commissioner",
      66:"Office of the Ombudsperson",
      67:"Office of the Police Complaint Commissioner",
      68:"Office of the Premier",
      70:"Oil and Gas Appeal Tribunal",
      71:"Passenger Transportation Board",
      72:"Property Assessment Appeal Board",
      73:"Public Guardian and Trustee",
      75:"Public Sector Employers' Council Secretariat",
      76:"Representative for Children and Youth",
      77:"Royal BC Museum",
      78:"Safety Standards Appeal Board",
      88:"Surface Rights Board of BC",
      84:"Workers' Compensation Appeal Tribunal",
    };
  }

