  /**
 * JS function for LSA ministry key array
 * Drupal.jquery
 * Written by Thayne Werdal March 2016
 */

  function ministry_list_complete() {
    ministry_list = {
      13:"Employment and Assistance Appeal Tribunal",
      15:"Aboriginal Relations and Reconciliation",
      16:"Advanced Education",
      17:"Agricultural Land Commission",
      18:"Agriculture",
      19:"BC Arts Council",
      20:"BC Farm Industry Review Board",
      21:"BC Human Rights Tribunal",
      22:"BC Pension Corporation",
      23:"BC Public Service Agency",
      24:"BC Review Board",
      25:"Board Resourcing and Development Office",
      26:"Children and Family Development",
      27:"",
      28:"Community Living BC",
      29:"Community, Sport and Cultural Development",
      30:"",
      31:"Crown Agencies Resource Office",
      32:"Destination BC",
      33:"Education",
      34:"Elections BC",
      35:"Energy and Mines",
      36:"Environment",
      37:"Environmental Appeal Board",
      38:"Environmental Assessment Office",
      39:"Finance",
      40:"Financial Institutions Commission",
      41:"",
      42:"Forest Appeals Commission           ",
      43:"Forest Practices Board",
      44:"Forests, Lands and Natural Resource Operations",
      45:"",
      46:"",
      47:"Government Communications and Public Engagement",
      48:"Health",
      49:"",
      50:"Intergovernmental Relations Secretariat",
      51:"International Trade",
      52:"Islands Trust",
      53:"Jobs, Tourism and Skills Training (Responsible for Labour)",
      54:"Justice",
      55:"",
      56:"",
      57:"Legislative Assembly",
      58:"Liquor Distribution Branch",
      59:"",
      60:"Natural Gas Development",
      61:"Office of the Auditor General",
      62:"Office of the Auditor General for Local Government",
      63:"",
      64:"Office of the Information and Privacy Commissioner",
      65:"Office of the Merit Commissioner",
      66:"Office of the Ombudsperson",
      67:"Office of the Police Complaint Commissioner",
      68:"Office of the Premier",
      69:"",
      70:"",
      71:"Passenger Transportation Board",
      72:"Property Assessment Appeal Board",
      73:"Public Guardian and Trustee",
      74:"Public Safety and Solicitor General",
      75:"Public Sector Employers' Council Secretariat",
      76:"Representative for Children and Youth",
      77:"Royal BC Museum",
      78:"Safety Standards Appeal Board",
      79:"Small Business and Red Tape Reduction",
      80:"Social Development and Social Innovation",
      81:"Technology, Innovation and Citizens' Services",
      82:"Transportation and Infrastructure",
      83:"",
      84:"Workers' Compensation Appeal Tribunal",
      85:"Surface Rights Board",
      86:"",
      87:"Office of the Conflict of Interest Commissioner",
      88:"Oak Bay Lodge Continuing Care Society",
    };
  }

