<?php

// /*
//  * Helper Function that returns a user's "alias"
//  */
// function _atwork_dual_user_map() {
//   // example: trevor's ID => Climate action's ID
//   return array(
//     21037 => 29103, // trevor - climate action
//     101 => 29103, // heather - climate action
// //    2096 => 39196, // rachelle - health bent
//     40159 => 39196, // jill bryant - health bent
//     1990 => 28285, // shelly - soapbox
//     41688 => 28285, // launa - soapbox
//     55608 => 28285, // launa - soapbox
//     1341 => 46380, // stephen - YFL
//     5410 => 46380, // nicole - YFL
//     6205 => 36870, // donna - arrc
//   );
// }

// /*
//  * Implementation of hook_views_pre_view()
//  *
//  * This is the view showing blogs on the user page - the alias's blogs
//  */
// function atwork_dual_user_views_pre_view(&$view, &$display_id, &$args) {
//   if ($view->name == 'content' && $view->current_display == 'page_2') {
//     if ($view->args) {
//       $dual_users = _atwork_dual_user_map();
//       if (isset($dual_users[$view->args[0]])) {
//         $view->args[0] = $dual_users[$view->args[0]];
//       }
//     }
//   }
// }

// /*
//  * Implementation of hook_node_presave()
//  *
//  * Save blogs as their alias
//  */
// function atwork_dual_user_node_presave($node) {
//   $dual_users = _atwork_dual_user_map();
//   if (isset($dual_users[$node->uid]) && $node->type == 'blog') {
//     $node->uid = $dual_users[$node->uid];
//   }
// }

// /*
//  * Implementation of hook_node_access()
//  *
//  * Allow users to access their alias's blogs
//  */
// function atwork_dual_user_node_access($node, $op, $account) {
//   $dual_users = _atwork_dual_user_map();
//   $type = is_string($node) ? $node : $node->type;
//   if (isset($dual_users[$account->uid]) && $type == 'blog' && is_object($node)) {
//     if ($dual_users[$account->uid] == $node->uid) {
//       return NODE_ACCESS_ALLOW;
//     }
//   }

//   // Returning nothing from this function would have the same effect.
//   return NODE_ACCESS_IGNORE;
// }

