<?php

/**
 * Implements hook_block_info().
 * A block that will hold a list that will replace the main menu - all controlled by jquery
 */
function atwork_mobile_block_info(){
  //dpm($blocks);
  $blocks = array();
  $blocks['atwork_mobile_menu_block'] = array(
    'info' => t("Atwork Mobile Menu Block"),
    );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function atwork_mobile_block_view($delta = '') {
  $block = array();

  switch($delta) {
    case ('atwork_mobile_menu_block'):
      $block['subject'] = '';
      $block['content'] = _atwork_menu_block_builder();
      // Add in block js
      drupal_add_js(drupal_get_path('module', 'atwork_mobile').'/atwork_mobile.js');
      break;
  }
  return $block;
}

/**
 * Helper function to seperate out the actual menue list
 *
 */

function _atwork_menu_block_builder(){
  // Lets build a well-id'd menu from unordered lists
  $output = <<<EOT
<div id="full_menu"> <i class="fa fa-bars" aria-hidden="true"></i>
  <ul id="atwork_menu">
    <li id = "atwork_menu_item_home" class="atwork_menu_top_level"><a href="/"> <span class="menu-title">Home</span> </a></li>
    <li id = "atwork_menu_item_tool" class="atwork_menu_top_level"><span class="menu-title"><i class="fa fa-plus" aria-hidden="true"></i> Top Sites</span>
      <ul id="atwork_menu_item_tool_menu">
        <li id = "atwork_menu_item_myhr" class="atwork_menu_nested"><a href="http://www2.gov.bc.ca/gov/content/careers-myhr" target="_blank">MYHR</a></li>
        <li id = "atwork_menu_item_tech_support" class="atwork_menu_nested"><a href="https://77000.gov.bc.ca" target="_blank">Technology Support</a></li>
        <li id = "atwork_menu_item_account_services" class="atwork_menu_nested"><a href="/tools/intranets">Ministry Intranets</a></li>
        <li id = "atwork_menu_item_myperformance" class="atwork_menu_nested"><a href="http://www2.gov.bc.ca/" target="_blank">gov.bc.ca</a></li>
      </ul>
    </li>
    <li id = "atwork_menu_item_news" class="atwork_menu_top_level"><span class="menu-title"><i class="fa fa-plus" aria-hidden="true"></i> News</span>
      <ul id="atwork_menu_item_news_menu">
        <li id = "atwork_menu_item_article" class="atwork_menu_nested"><a href="/news">Articles</a></li>
        <li id = "atwork_menu_item_executive_messages" class="atwork_menu_nested"><a href="/executive-messages"> Executive Messages </a></li>
        <li id = "atwork_menu_item_newsletters" class="atwork_menu_nested"><a href="/newsletters"> Newsletters </a></li>
        <li id = "atwork_menu_item_videos" class = "atwork_menu_nested"><a href = "/videos"> Videos </a></li>
      </ul>
    </li>
    <li id="atwork_menu_item_about_the_bc_public_service" class="atwork_menu_top_level"><span class="menu-title"><i class="fa fa-plus" aria-hidden="true"></i> About the BC Public Service</span>
      <ul id="atwork_menu_item_abps_menu">
        <li id="atwork_menu_item_our_organization" class="atwork_menu_nested"><a href="/our-organization">Our Organization</a></li>
        <li id="atwork_menu_item_our_values" class="atwork_menu_nested"><a href="/org/bcps-values">Our Values</a></li>
        <li id="atwork_menu_item_standards_of_conduct" class="atwork_menu_nested"><a href="http://www2.gov.bc.ca/gov/content/careers-myhr/managers-supervisors/employee-labour-relations/conditions-agreements/policy#standards" target="_blank">Standards of Conduct</a></li>
        <li id="atwork_menu_item_community_involvement" class="atwork_menu_nested"><a href="/community-involvement">Community Involvement</a></li>
        <li id="atwork_menu_item_where_ideas_work" class="atwork_menu_nested"><a href="/org/where-ideas-work-brand">Where Ideas Work</a></li>
        <li id="atwork_menu_item_core_policies" class="atwork_menu_nested"><a href="http://www2.gov.bc.ca/gov/content/governments/services-for-government" target="_blank">Services and Policies</a></li>
      </ul>
    </li>
    <li id="atwork_menu_item_our_community" class="atwork_menu_top_level"><span class="menu-title"><i class="fa fa-plus" aria-hidden="true"></i> Our Community</span>
      <ul id="atwork_menu_item_our_community_menu">
        <li id="atwork_menu_item_employee_profiles" class="atwork_menu_nested"><a href="/employees">Employee Profiles</a></li>
        <li id="atwork_menu_item_executive_profiles" class="atwork_menu_nested"><a href="/executive-team">Executive Profiles</a></li>
        <li id="atwork_menu_item_executive_team" class="atwork_menu_nested"><a href="/exec/profiles">Executive Team</a></li>
        <li id="atwork_menu_item_groups" class="atwork_menu_nested"><a href="/groups">Groups</a></li>
        <li id="atwork_menu_item_blogs" class="atwork_menu_nested"><a href="/blogs">Blogs</a></li>
        <li id="atwork_menu_item_polls" class="atwork_menu_nested"><a href="/polls">Polls</a></li>
        <li id="atwork_menu_item_events" class="atwork_menu_nested"><a href="/announcements">Events</a></li>
        <li id="atwork_menu_item_classifieds" class="atwork_menu_nested"><a href="/classifieds">Classifieds</a></li>
        <li id="atwork_menu_item_recent_comments" class="atwork_menu_nested"><a href="/recent-comments">Comments</a></li>
      </ul>
    </li>
    <li id="atwork_menu_item_engagement_recognition" class="atwork_menu_top_level"><span class="menu-title"><i class="fa fa-plus" aria-hidden="true"></i> Engagement &amp; Recognition</span>
      <ul id="atwork_menu_item_engagement_recognition_menu">
        <li id="atwork_menu_item_ecards" class="atwork_menu_nested"><a href="/ecards">Ecards</a></li>
        <li id="atwork_menu_item_r2r" class="atwork_menu_nested"><a href="/region-to-region">Region to Region</a></li>
        <li id="atwork_menu_item_wes" class="atwork_menu_nested"><a href="/wes">Work Environment Survey</a></li>
        <li id="atwork_menu_item_premiers_awards" class="atwork_menu_nested"><a href="/career/premiers-awards">Premier's Awards</a></li>
        <li id="atwork_menu_item_lsa" class="atwork_menu_nested"><a href="/career/long-service-awards">Long Service Awards</a></li>
      </ul>
    </li>
  </ul>
</div>


EOT;
  return $output;
}
