<?php

function atwork_relationships_init() {
  $js = <<<EOT
function atwork_relationships_ajax_load(op, uid, rtid) {
  jQuery(".atwork-relationship-action.uid-" + uid).load("/atwork-relationship/" + op + "/" + uid + "/" + rtid);
  jQuery(".block-refresh-button").each(function(){
    jQuery(this).click();
  });
  return false;
}
EOT;

// This allows us to ajax block content on the profiles page

  $js2 = <<<EOT
jQuery(document).ready(function(){
  jQuery(".atwork-relationship-action").mousedown(function(){
    jQuery(".block-refresh-button").each(function(){
      jQuery(this).click();
    });
  });
});
EOT;

    drupal_add_js($js, 'inline');
    //drupal_add_js($js2, 'inline');

}

function atwork_relationships_get_link($account) {
  global $user;

  $relationships = user_relationships_load(array(
    'requester_id' => $user->uid,
    'requestee_id' => $account->uid,
    'rtid' => 1,
  ));

  if ($relationships) {
    foreach ($relationships as $rid => $relationship) {
      $relationship_link = '<a href="#" title="Click to unfollow colleague" onclick="atwork_relationships_ajax_load(\'remove\', \'' . $account->uid . '\', \'' . $rid . '\'); return false;">Following</a>';
    }
  }
  else {
    $relationship_link = '<a href="#" title="Click to follow colleague" onclick="atwork_relationships_ajax_load(\'add\', \'' . $account->uid . '\', \'1\'); return false;">Follow</a>';
  }

  return '<div class="atwork-relationship-action uid-' . $account->uid . '">' . $relationship_link . '</div>';
}

function atwork_relationships_views_pre_render(&$view) { 
  // show the follow/ing links if on these Views pages 
  if ($view->name == 'people_admin' && ($view->current_display == 'public_page' || $view->current_display == 'page_following2' || $view->current_display == 'page_followers2') && module_exists('user_relationships')) {
    foreach ($view->result as &$result) {
      $account = user_load($result->uid);
      $relationship_link = atwork_relationships_get_link($account);

      if (isset($result->field_field_gal_title[0]['rendered']['#markup'])) {
        $result->field_field_gal_title[0]['rendered']['#markup'] .= $relationship_link;
      }
      else {
        $result->field_field_gal_title[0]['rendered']['#markup'] = $relationship_link;
      }
    }
  }
}

/**
 * Implements hook_menu();
 */
function atwork_relationships_menu() {
  $items['atwork-relationship/%/%user/%'] = array(
    'title' => 'Make Relationships',
    'type' => MENU_CALLBACK,
    'page callback' => 'atwork_relationships_page_callback',
    'page arguments' => array(1,2,3),
    'access arguments' => array('access content'),
    'delivery callback' => 'atwork_relationships_delivery_callback',
  );
  return $items;
}

function atwork_relationships_page_callback($op, $account, $id) {
  switch ($op) {
    case 'add':
      global $user;
      $relationship = user_relationships_request_relationship($user, $account, $id);
      return '<a href="#" onclick="atwork_relationships_ajax_load(\'remove\', \'' . $account->uid . '\', \'' . $relationship->rid . '\'); return false;">Following</a>';
      break;

    case 'remove':
      $relationships = user_relationships_load(array('rid' => $id));
      user_relationships_delete_relationship($relationships[$id], $account, $op);
      return '<a href="#" onclick="atwork_relationships_ajax_load(\'add\', \'' . $account->uid . '\', \'1\'); return false;">Follow</a>';;
      break;
  }
}

function atwork_relationships_delivery_callback($page_callback_result) {
  print $page_callback_result;
}


/**
 * Implements hook_user_view
 * Code that adds a follow button and ajax callbacks on profile pages
 */

function atwork_relationships_user_view($account, $view_mode, $langcode) {
  if($view_mode == 'full' && module_exists('user_relationships')){
    global $user;
    // User should not see their own follow button
    if($account->uid === $user->uid){
      return;
    }

    // Build a link and then wrap it in a button.
    $relationship_link = atwork_relationships_get_link($account);
    if (isset($account->content['field_gal_first_name'][0]['#markup'])) {
      // Add button to the markup for first name (that is altered into full name)
      // The full name part of this was moved from atwork_profiles - as noted there.
      $account->content['field_gal_first_name'][0]['#markup'] = t(_atwork_full_name($account)) . $relationship_link ;
    }
    else {
      $result->field_field_gal_title[0]['rendered']['#markup'] .= $relationship_link;
    }
  }
}

/**
 *  helper function to add in follow button on blog node view
 */
function _atwork_relationships_button_add(&$output, $account){
    // Build a link and then wrap it in a button.
    $relationship_link = atwork_relationships_get_link($account);

    return($output .= $relationship_link);
}


/**
 * Implementation of hook_block_view_MODULE_DELTA_alter
 * Code to show following/followers blocks only on user and user/* pages.
 */
function atwork_relationships_block_view_alter(&$data, $block){
  switch ($block->delta){
    // Grab relationship blocks - same process on either, so we can fall through
    case("people_admin-block_following"):
    case("people_admin-block_followers"):
      // Block is set, so lets check if we are on the right page
      if(isset($block->visibility) && $block->visibility == 1){
        $url_check = $_SERVER['REQUEST_URI'];
        $url_parts_check = explode( '/', $url_check);
        // Don't want to make the block disappear on ajax reload
        if($url_parts_check[1] == "block_refresh"){
          return;
        }
        // If we are down the path further than user/[idir], then hide these blocks
        if(count($url_parts_check) > 3){
          $data['content']['#access'] = false;
        }
      }
    break;
  }
}
