<?php

/*
 * Implementation of hook_views_pre_view()
 *
 * Creating a full name author field
 *
 */
function atwork_status_update_views_pre_view(&$view, &$display_id, &$args) {
  if ($view->name == 'status_update' && $view->current_display == 'page') {
    dpm($view);
    if ($view->args) {
      $author = user_load_by_name($view->args[0]);
      if ($author) {
        $view->args[0] = $author->uid;
      }
      else {
        drupal_not_found();
      }
    }
  }
}

