//126 atwork_events
/**
 * Implements hook_views_pre_render
 * @param  &$view
 * To clear group events out of calendar
 */
function atwork_events_views_pre_render(&$view){
  if($view->name == 'calendar'){
    foreach($view->result as $key){
      if(isset($key->_field_data['nid']['entity']->og_group_ref) && $key->_field_data['nid']['entity']->og_group_ref) {
        continue;
      } elseif($view->nid == '27000' ) {
        continue;
      } else {
        $result_no_group[] = $key;
      }
    }
    $view->result = $result_no_group;
  }
}


//viwes-ical-vevent.tpl.php
<?php

/**
 * @file
 * Default theme implementation to display an iCal event.
 *
 * If you are editing this file, remember that all output lines generated by it
 * must end with DOS-style \r\n line endings, and not Unix-style \n, in order to
 * be compliant with the iCal spec.
 *
 * @see http://tools.ietf.org/html/rfc5545#section-3.1
 *
 * @ingroup themeable
 */

$title = '';
print "BEGIN:VEVENT\r\n";
foreach ($fields as $id => $field):
  $field->content = htmlspecialchars_decode($field->content, ENT_QUOTES);
  
  if ($id == 'title') {
    $title = $field->content;
  }
  
  if ($id == 'field_date' || $id == 'field_date_1') {
    
    $field->content = strip_tags($field->content);
    
    if (strpos($field->content, ' (All day)')) {
      $field->content = substr_replace($field->content, '', 8, strlen($field->content));
      $field->label_html = $field->label . ';VALUE=DATE:';
      
      // if all day the end date should be the day after what is entered
      if ($id == 'field_date_1') {
        $day_after = mktime(
          0, // hour
          0, // minute
          0, // second
          date('m', strtotime($field->content)), // month
          (date('d', strtotime($field->content)) + 1), // day - adding one day to it
          date('Y', strtotime($field->content)) // year
        );
        $field->content = date('Ymd', $day_after);
      }
      
    }
    else {
      $field->content = substr_replace($field->content, '', -1);
    }
  }
  
  if ($id == 'body_1') {
    // load node and make link to it
    $footer = '';
    if (isset($field->handler->view->args[0])) {
      $node = node_load($field->handler->view->args[0]);
      $footer = '<br /><br />---<br />View <a href="' . url('node/' . $node->nid, array('absolute' => TRUE)) . '">' . $node->title . '</a> on @Work';
    }
    
    $field->content = str_replace("\n", '\n', $field->content);
    // Don't want the footer for these special case events
    if(isset($field->raw) && $field->raw == '27000'){
      $field->content = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">\n<HTML>\n<HEAD>\n<META HTTP-EQUIV="Content-Type" CONTENT="text/html\; charset=iso-8859-1">\n<META NAME="Generator" CONTENT="MS Exchange Server version 08.03.0330.000">\n<TITLE>' . $title . '</TITLE>\n</HEAD>\n<BODY><FONT FACE="Calibri">\n<!-- Converted from text/rtf format -->\n\n' . $field->content . '</FONT></BODY>\n</HTML>';
    } else {
      $field->content = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">\n<HTML>\n<HEAD>\n<META HTTP-EQUIV="Content-Type" CONTENT="text/html\; charset=iso-8859-1">\n<META NAME="Generator" CONTENT="MS Exchange Server version 08.03.0330.000">\n<TITLE>' . $title . '</TITLE>\n</HEAD>\n<BODY><FONT FACE="Calibri">\n<!-- Converted from text/rtf format -->\n\n' . $field->content . $footer . '</FONT></BODY>\n</HTML>';
    }
  }
  
  if (!empty($field->separator)):
   print $field->separator;
  endif;
  
  print $field->wrapper_prefix;
  print $field->label_html;
  print $field->content;
  print $field->wrapper_suffix;
  print "\r\n";
  
endforeach;
// Adding in a 15 min alert for ical sent on specific node. This is a test for the PECSEF campaign
if(isset($fields['body_1']->raw) && $fields['body_1']->raw == '27000'){
  print "BEGIN:VALARM\r\n";
  print "TRIGGER:-PT15M\r\n";
  print "REPEAT:1\r\n";
  print "DURATION:PT15M\r\n";
  print "ACTION:DISPLAY\r\n";
  print "DESCRIPTION:Reminder\r\n";
  print "END:VALARM\r\n";
}
  
print "END:VEVENT\r\n";
