<?php
/**
 * Implements hook_init();
 */
function atwork_dev_init() {
  // ensure our reroute_email module is enabled on dev and test environments
  if (!_atwork_production_environment()) {
    if (!variable_get(REROUTE_EMAIL_ENABLE, 0)) {
      variable_set(REROUTE_EMAIL_ENABLE, 1);
      variable_set(REROUTE_EMAIL_ENABLE_MESSAGE, 1);
      variable_set(REROUTE_EMAIL_ADDRESS, ATWORK_TECHNICAL_EMAIL);
    }
  }
  else {
    if (variable_get(REROUTE_EMAIL_ENABLE, 0)) {
      variable_set(REROUTE_EMAIL_ENABLE, 0);
      variable_set(REROUTE_EMAIL_ENABLE_MESSAGE, 1);
      variable_set(REROUTE_EMAIL_ADDRESS, ATWORK_TECHNICAL_EMAIL);
    }
  }
}

/**
 * Implements hook_tokens_alter();
 *
 * Problems when drupal exposes its server's machine name
 *
 * IE: arrowsmith.dmz
 */
function atwork_dev_tokens_alter(array &$replacements, array $context) {
  if ($context['type'] == 'subs' && isset($replacements['[subs:unsubscribe-url]']) && isset($context['data']['subs']['unsubscribe_path'])) {
    $replacements['[subs:unsubscribe-url]'] = 'https://' . ATWORK_PRODUCTION_ENVIRONMENT . '/' . $context['data']['subs']['unsubscribe_path'];
  }
  if ($context['type'] == 'node' && isset($replacements['[node:url]'])) {
    $node = $context['data']['node'];
    $replacements['[node:url]'] = 'https://' . ATWORK_PRODUCTION_ENVIRONMENT . '/' . url('node/' . $node->nid);
  }
  if ($context['type'] == 'comment') {

  }
  if ($context['type'] == 'url' && isset($replacements['[subs:category:url:absolute]'])) {
    $replacements['[subs:category:url:absolute]'] = 'https://' . ATWORK_PRODUCTION_ENVIRONMENT . '/' . url($context['data']['path']);
  }
}

/**
 * Implements hook_form_alter();
 *
 * Adds a visual cue notifying us we are on a test/dev site
 */

/*
function atwork_dev_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
	if (_atwork_test_environment()) {
      $form['#suffix'] = '<div id="atwork-env">TEST ENVIRONMENT</div>';
    }
    if (_atwork_dev_environment()) {
      //$form['#suffix'] = '<div id="atwork-env">DEV ENVIRONMENT</div>';
    }
  }
}
*/
/*
 * Implements template_preprocess_html
 *
 * body class for our test/dev environments
 */
function atwork_dev_preprocess_html(&$variables) {
	if (_atwork_test_environment()) {
    $variables['classes_array'][] = 'test-env';
  }
  if (_atwork_dev_environment()) {
    $variables['classes_array'][] = 'dev-env';
  }
}
