<?php

/*
 * Implementation of hook_form_FORMID_alter()
 *
 * On user edit page hide profile form if not an executive
 */
function atwork_executive_profiles_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    // if not an exec hide public profile field
    $account = $form['#user'];
    global $user;
    if (!in_array('executive', $account->roles) && !user_access('administer users')) {
      $form['notify']['#access'] = FALSE;
    }
    if (!in_array('executive', $account->roles) && (!in_array('administrator', $user->roles) && !in_array('editor', $user->roles))) {
      $form['field_trusted_assistants']['#access'] = FALSE;
    }
  }
}

/*
 * Implementation of hook_atwork_profiles_user_edit_access_alter()
 *
 * Cancel the functionality of field_trusted_assistants unless account to edit is an executive
 */
function atwork_executive_profiles_atwork_profiles_user_edit_access_alter(&$return, $account) {
  if (!user_access('administer users') && $GLOBALS['user']->uid != $account->uid && !in_array('executive', $account->roles)) {
    $return = FALSE;
  }
}

/*
 * Implementation of hook_atwork_profiles_user_view_access_alter()
 *
 * Prevent the viewing of all user pages except executives - Despite permissions!
 */
function atwork_executive_profiles_atwork_profiles_user_view_access_alter(&$return, $account) {
  global $user;

  if (is_object($account)) {
    if ($user->uid != $account->uid && !in_array('executive', $account->roles) && !user_access('administer users')) {
      // Going to return the profile either way - just need to hide the custom fields
      $return = TRUE;
    }
    if (in_array('executive', $account->roles) && in_array('executive', $user->roles)) {
      $return = TRUE;
    }
  }
}

