<?php
/**
 * @file
 * set and get views_user_options for the items_per_page value
 * after a page reload.
 * 
 * Handles 3 values: items per page, sort by and sort order
 * 
 * All 3 are handled differently!
 * 
 * "items per page" set by $view->set_items_per_page()
 * "sort by" set by $_GET['sort_by']
 * "sort order" set by $form['sort_order']['#default_value']
 * 
 */

/**
 * Implements hook_form_views_exposed_form_alter().
 */
//function views_fix_exposed_filter_form_views_exposed_form_alter(&$form, &$form_state, $form_id){
//  global $user;
//
//  // If the exposed filter form was submitted save the values in $user->data
//  if(isset($form_state['input']['items_per_page'])){
//    $comments_per_page = $form_state['input']['items_per_page'];
//  }
//  
//  if(isset($form_state['input']['sort_order'])){
//    $sort_order = $form_state['input']['sort_order'];
//  }
//  
//  // only set the cookie if the form was submitted
//  if (isset($comments_per_page) && isset($sort_order)) {
//    //setcookie('views_user_options', serialize($views_user_options), time()+60*60*24*365, '/');
//    $edit = array(
//      'data' => array(
//        'atwork_comments_per_page' => $comments_per_page,
//        'atwork_sort_order' => $sort_order,
//      ),
//    );
//    user_save($user, $edit);
//  }
//  
//  // if the form wasn't submitted and there is no data in the cookie we can go now
//  if (!isset($user->data['atwork_comments_per_page']) && !isset($user->data['atwork_sort_order'])) {
//    return;
//  }
//  
//  // we found data in $user->data, set the form accordingly
//  $form['items_per_page']['#default_value'] = $user->data['atwork_comments_per_page'];
//  $form['sort_order']['#default_value'] = $user->data['atwork_sort_order'];
//}

/**
 * Implements hook_views_pre_build().
 */
function views_fix_exposed_filter_views_pre_build(&$view){
//  global $user;
//  
//  // if there is no data in $user->data we can leave now
//  if (!isset($user->data['atwork_comments_per_page']) && !isset($user->data['atwork_sort_order'])) {
//    return;
//  }
//  else {
//    $items_per_page = $user->data['atwork_comments_per_page'];
//  }
//  
//  if ($items_per_page == 'All') {
//    $items_per_page = 0;
//    
//    // this is a hack to prevent undefined errors when the user has selected "all" in
//    // items to display. It is a hack because we are setting the pager id to 1 but
//    // we don't actually know what it is here from $view
//    //$GLOBALS['pager_total'][1] = 0;
//  }
//  
//  // set items per page
//  $view->set_items_per_page($user->data['atwork_comments_per_page']);
  
  // set sort by
//  if (isset($views_user_options[$view->name][$display]['sort_by']) && !isset($_GET['sort_by'])) {
//    $_GET['sort_by'] = $views_user_options[$view->name][$display]['sort_by'];
//    dpm($view);
//  }
  
}

