<?php

/*
 * Implementation of hook_init()
 *
 * Make the comment text area start with the text editor disabled.
 */
function atwork_formats_init() {

  drupal_add_js('(function ($) { '
      . '$( document ).ready(function() { '
      . '$( "#wysiwyg-toggle-edit-comment-body-und-0-value" ).trigger( "click" );'
      . '}); }(jQuery));',
      array('type' => 'inline', 'scope' => 'footer', 'weight' => 99));
}

/**
 * Implements hook_element_info_alter()
 *
 * Adds an #after_build function to all text_format elements.
 */
function atwork_formats_element_info_alter(&$types) {
  $types['text_format']['#after_build'][] = 'atwork_formats_after_build';
}

/*
 * after_build Callback
 *
 * Set various defaults to input formats
 *
 * Do some fixes related to hiding the input format form and wysiwyg module
 *
 * This is stuff better_formats module would do without the over-head
 */
function atwork_formats_after_build($element, &$form_state) {
  if (isset($element['format'])) {

    global $user;

    // always hide guidelines and help.
    $element['format']['guidelines']['#access'] = FALSE;
    $element['format']['help']['#access'] = FALSE;

    if (isset($element['#field_name']) && $element['#field_name'] == 'field_summary') {
      $element['format']['format']['#options'] = array(
        'comment' => 'Comment',
      );
    }

    if (isset($element['#field_name']) && $element['#field_name'] == 'field_transcript') {
      $element['format']['format']['#options'] = array(
        'comment' => 'Comment',
      );
    }

    if (isset($element['#field_name']) && $element['#field_name'] == 'field_blog_profile') {
      $element['format']['format']['#options'] = array(
        'filtered_no_editor' => 'Filtered HTML without an Editor',
      );
    }

    // #entity_type not always set
    if (!isset($element['#entity_type'])) {
      $entity_type = FALSE;
    }
    else {
      $entity_type = $element['#entity_type'];
    }
    // comments always get comment input format
    if ($entity_type == 'comment') {
      $element['format']['format']['#options'] = array(
        'comment' => 'Comment',
      );
    }

    if (count($element['format']['format']['#options']) == 1) {
      $element['format']['#attributes']['class'][] = 'element-invisible';
    }
    else {
      $element['format']['#title'] = t('Input format');
      $element['format']['#collapsible'] = TRUE;
      $element['format']['#collapsed'] = TRUE;
      $element['format']['#attributes']['class'][] = 'collapsible';
      $element['format']['#attributes']['class'][] = 'collapsed';
    }
  }

  return $element;
}

