<?php

function _atwork_prem_awards_ministry_contacts() {
  return array(
    // All ministry contacts must be included in the exact same order as the ministry dropdown (i.e. aboriginal contact in array [1], advanced ed in array [2])
  		// All ministry contacts must be included in the exact same order as the ministry dropdown (i.e. aboriginal contact in array [1], advanced ed in array [2])
  		1 => 'Kristin.Barnes@gov.bc.ca', //Ministry of Advanced Education, skills and Training
  		2 => 'Shawna.Lyttle@gov.bc.ca', //Agriculture
  		3 => 'Catherine.Dooner@gov.bc.ca', // Attorney General
  		4 => 'Kate.Mitchell@gov.bc.ca', //Children & Family Development
  		5 => 'Jeannette.Cook@gov.bc.ca', // Citizens’ Services
  		6 => 'Courtney.Ashcroft@gov.bc.ca', //Education
  		7 => 'Katie.Hulbert@gov.bc.ca', // Energy, Mines and Petroleum Resources
  		8 => 'Karla.Kennedy@gov.bc.ca', //Environment and Climate Change Strategy
  		9 => 'Jennifer.Meadows@gov.bc.ca', //Environment Assessment Office
  		10 => 'Jennifer.Michell@gov.bc.ca', //Finance
  		11 => 'Andrea.Wood@gov.bc.ca', //Forests, Lands, Natural Resource Operations and Rural Development
  		12 => 'Rita.Chand@gov.bc.ca', //Government Communications and Public Engagement
  		13 => 'Brieana.Murray@gov.bc.ca', //Health
  		14 => 'Karen.Williams@gov.bc.ca', //Indigenous Relations & Reconciliation
  		15 => 'Lorna.Hay@gov.bc.ca', //Jobs, Trade and Technology
  		16 => 'Sveah.Hourston@gov.bc.ca', //Labour
  		17 => 'Kimberley.Guidoriagao@gov.bc.ca', // Mental Health and Addictions
  		18 => 'Susan.Paton@gov.bc.ca', // Municipal Affairs and Housing
  		19 => 'Catherine.Dooner@gov.bc.ca', //Public Safety & Solicitor General
  		20 => 'Carolyn.Babakaiff@gov.bc.ca', // Social Development and Poverty Reduction
  		21 => 'Andrea.Berkes@gov.bc.ca',  // Tourism, Arts and Culture
  		22 => 'Lea.Plamondon@gov.bc.ca',  // Transportation and Infrastructure
  		23 => 'Kelly.Brubacher@gov.bc.ca', //BC Public Service Agency
  		24 => 'Rita.Chand@gov.bc.ca', // Government Communications and Public Engagement
  		25 => 'andrew.james@bcldb.com', // Liquor Distribution Branch
  		26 => 'smaloney@Trustee.bc.ca ', // Public Guardian and Trustee
  );
}

function _atwork_prem_awards_headers() {
  return array(
    1 => '<h3>CROSS GOVERNMENT INTEGRATION</h3>This award, which is presented <em>regionally and provincially</em>, recognizes two or more BC Public Service organizations that have collaboratively delivered a program or service that has resulted in substantial benefits to clients, the public service, or citizens.',
    2 => '<h3>INNOVATION</h3>This award recognizes groups, teams or organizations in the BC Public Service who have developed and transformed new ideas into tangible initiatives, programs or projects. By applying a user-centric or citizen-centric approach, innovations streamline business processes, leverage technology or pursue creative solutions to fulfill organizational mandates. Considerations may include but are not limited to
	    <ul>
        <li>Generating breakthrough ideas, fresh perspectives and new opportunities</li>
        <li>Using new technology or tools to enhance program and service delivery or improve upon existing processes and procedures such as Behavioural Insights, Data Science, Service Design or Agile Methodology</li>
        <li>Improving performance by doing things that may be unique, leading-edge or new to the public sector</li>
        <li>Changing the organizational culture or traditional approach to management or problem solving</li>
        <li>Experimental or innovative mindset whereby openness to change, taking calculated risks and challenging the status quo to try something new resulted in a measurable outcome</li>
        <li>Adapting and refining the approach or initiative when things have not worked well and learning from the setbacks/mistakes</li>
      </ul>',

    3 => '<h3>LEADERSHIP</h3>This award recognizes a BC Public Service employee who demonstrates the highest levels of integrity and exemplary leadership abilities either leading a team or organization, or a substantial project, process or initiative. Considerations may include but are not limited to
       <ul>
         <li>Ability to create, communicate and implement a clear and compelling vision</li>
         <li>Ability to establish trust, motivate, empower and receive high satisfaction ratings from their employees</li>
         <li>Ethical leadership practices</li>
         <li>Commitment to diversity and inclusion in both the work environment and the development of programs, policies and services</li>
         <li>Advocating meaningful engagement and learning with Indigenous peoples to support and facilitate reconciliation</li>
         <li>Anticipating future trends and working with others to develop strategies to meet future challenges</li>
         <li>Commitment to succession management through knowledge transfer, support for continuous learning and mentorship</li>
         <li>Commitment to service delivery in exceeding the needs/expectations of internal or external clients</li>
         <li>Experimental or innovative mindset whereby openness to change, taking calculated risks and challenging the status quo to try something new resulted in a measurable outcome</li>
       </ul>',

    4 => '<h3>ORGANIZATIONAL EXCELLENCE</h3>This award recognizes one or more BC Public Service organizations that have delivered a program, service or initiative resulting in substantial benefits to their organization(s), the public service or citizens. Considerations may include but are not limited to
       <ul>
         <li>Citizen-centric or customer-centric approach at the heart of the design and/or implementation of a policy/project</li>
         <li>Inclusive employee or citizen engagement practices with diverse stakeholder groups</li>
         <li>Improving quality, cost-effectiveness or productivity of services to internal stakeholders</li>
         <li>Improving government-to-business or government-to-citizen service delivery</li>
         <li>Measurable benefits to either their organization(s) and/or the citizens of British Columbia through process improvements to transform business practices, and/or support sustainable revenue generation or savings</li>
	     </ul>',

    5 => '<h3>PARTNERSHIP</h3>This award recognizes joint ventures or multi-party initiatives between BC Public Service organizations and organizations in the broader public sector, other levels of government, Indigenous communities or in the private or non-profit sectors. Considerations may include but are not limited to
			<ul>
        <li>Developing and managing sustained strategic partnerships with other government, private sector, volunteer or non-profit organizations, integrating policy and/or service delivery to better serve British Columbians</li>
        <li>Measurable benefits to either their organization(s) and/or the citizens of British Columbia through process improvements transforming business practices, and/or supporting sustainable revenue generation or savings</li>
        <li>Inclusive employee or citizen engagement practices with diverse stakeholder groups</li>
        <li>Improving the quality, cost-effectiveness, or productivity of services to internal stakeholders</li>
        <li>Improving government-to-business or government-to-citizen program or service delivery</li>
			</ul>',

    6 => '<h3>LEGACY</h3>This award recognizes individuals who have made exceptional and lasting contributions to the BC Public Service and/or the province during a public service career of at least 15 years. The contributions may cover a nominee’s entire career or portions of it, provided the contribution has a lasting and ongoing positive impact. Considerations may include but are not limited to
			<ul>
        <li>Impact on peers, the internal operations and/or external organizations</li>
        <li>Contributions to the development or application of best practices in their field of expertise</li>
        <li>Experimental or innovative mindset whereby openness to change, taking calculated risks and challenging the status quo to try something new resulted in a measurable outcome</li>
        <li>Embodying the ideal vision of leadership within the BC Public Service</li>
        <li>Commitment to diversity and inclusion in both the work environment and in the development of programs, policies and services</li>
        <li>Advocating meaningful engagement and learning with Indigenous peoples to support and facilitate reconciliation</li>
        <li>Superior leadership through complex situations including large-scale initiatives, managing and mitigating risks, creatively solving problems and implementing solutions</li>
        <li>Achieving outcomes despite constraints such as technical, organizational and financial</li>
        <li>Commitment to succession management through knowledge transfer, support for continuous learning and mentorship</li>
			</ul>',

    7 => '<h3>EMERGING LEADER</h3>This award recognizes a BC Public Service employee 40 years and under and at or below the level of director who has made a significant impact in their ministry, division, workgroup or the greater BC Public Service early in their career. Considerations may include but are not limited to
      <ul>
        <li>Superior formal or informal leadership with colleagues across all levels of the organization</li>
        <li>Superior formal or informal leadership through innovative problem solving, team building, collaboration and a strong client service orientation</li>
        <li>Thought leader who can articulate a strong case for change, self-motivate and motivate others through change and demonstrate success through measurable project/program outcomes</li>
        <li>Commitment to diversity and inclusion in both the work environment and in the development of programs, policies and services</li>
        <li>Ethical leadership practices</li>
        <li>Supporting innovation, new technology and best practices</li>
  		</ul>',

    8 => '<h3>EVIDENCE-BASED DESIGN</h3>This award recognizes groups, teams or organizations in the BC Public Service whose work is outstanding in the area of evidence-based or evidence-informed policy or program development, and the process by which the policy or program was designed. This category showcases excellence in policy or program development for internal government or citizen-facing initiatives. Considerations may include but are not limited to
  		<ul>
        <li>The evidence-based or evidence-informed process in which the policy framework was designed</li>
        <li>The policy cycle including clear problem identification, analysis, evidence-based or evidence-informed decision making, implementation and evaluation</li>
        <li>Using foundational policy analysis tools to support recommendations such as data and/or cost analysis, cross-jurisdictional and/or international reviews or peer reviewed research</li>
        <li>Using new technology or tools such as Data Science, Service Design, etc. to support policy recommendations</li>
        <li>Inclusive citizen engagement practices reflecting a diverse population within British Columbia such as the use of GBA+ and other inclusive program development tools</li>
  		</ul>',

    9 => '<h3>REGIONAL IMPACT</h3>This award recognizes groups, teams or organizations within the BC Public Service who have developed and delivered programs, projects and initiatives benefiting citizens in a specific location (town, city, municipality or region). Considerations may include but are not limited to
  		<ul>
        <li>Projects or initiatives directly benefitting citizens in the specific town, city, municipality or region</li>
        <li>Recognizing merit regardless of the project/initiative’s size or pedigree and those with less visibility which are more grassroots in nature</li>
        <li>Generating innovative ideas, fresh perspectives and new opportunities</li>
        <li>Citizen engagement practices with diverse stakeholder groups</li>
        <li>Citizen-centric or customer-centric approach at the heart of the design and/or implementation of a policy/project</li>
        <li>Developing and managing sustained strategic partnerships with local government, Indigenous, private sector, volunteer or non-profit organizations, integrating policy and/or service delivery to better serving British Columbians in a specific location</li>
        <li>Experimental or innovative mindset whereby openness to change, taking calculated risks and challenging the status quo to try something new resulted in a measurable outcome</li>
  		</ul>',

  );
}

function _atwork_prem_awards_questions() {
  $translations = array();
  $translations[1][1] = "The submission should describe two or more BC Public Service organizations for taking an integrated approach to service/program delivery that produces substantial benefits.";
  $translations[1][2] = "Breadth and degree of impact the program or service has had on its intended audience (internal or external)";
  $translations[1][3] = "Alignment with public service vision, values and overall government direction";
  $translations[1][4] = "Complexity involved including:<ul><li>the scope of the initiative;</li><li>risks encountered and overcome;</li><li>creativity demonstrated;</li><li>technical or organizational difficulties addressed;</li><li>financial constraints managed</li></ul>";
  $translations[1][5] = "Application of and/or development of best practices including:<ul><li>Attention to cross-government processes critical for meeting client needs;</li><li>Involvement of clients/suppliers/partners in integration initiatives (e.g.: problem solving);</li><li>Use of external resources and or benchmarking to compare performance and stimulate ongoing improvement.</li></ul>";
  $translations[1][6] = '';
  $translations[1][7] = '';
  $translations[1][8] = '';
  $translations[1][9] = '';

  /* Innovation */
  $translations[2][0] = 'In this section, provide a brief statement that summarizes or restates the main points of the nomination (goal and achievement). The purpose of the summary is to give the adjudicators and judges a condensed and objective account of the main idea(s) and accomplishment(s) of the nomination.<br><br>
		<em>(Note that this section will be used by the Premier’s Awards team for communications purposes if this nomination is selected as a finalist.)</em>';
  $translations[2][1] = "To establish a background that will provide perspective to the work achieved, briefly describe why the new innovative approach was undertaken.";
  $translations[2][2] = "<strong>Complexity:</strong><br />Describe the scope and scale of the new initiative, streamlined business processes, technology, or creative solution developed including, but not limited to:
		<ul><li>Size of the project, process, technology solution;</li>
		<li>Risks encountered;</li>
		<li>Challenges around introducing a new approach to solve a challenging problem;</li>
		<li>Technical or organizational difficulties addressed;</li>
		<li>Financial constraints managed.</li></ul>";
  $translations[2][3] = "<strong>Approach:</strong><br />Describe how the new initiative, product or service was developed from inception to delivery and transformed new ideas into tangible initiatives including, but not limited to:
		<ul><li>The process used to generate breakthrough ideas, fresh perspectives and new opportunities;</li>
		<li>The use of new technology or tools to enhance program and service delivery or improve upon existing processes and procedures (i.e. Behavioural Insights, Data Science, Service Design,  Agile Methodology, etc.);</li>
		<li>Application of a user-centric or citizen-centric approach in the development of the initiative/program; </li>
		<li>Adapting and refining the approach or initiative when things did not work well and learning from the setbacks/mistakes;</li>
		<li>Explain how the team managed and overcame risks encountered to adapt and refine the process; </li>
		<li>Creativity in the design or redesign of the programs or services.</li></ul>";
  $translations[2][5] = "<strong>Impact:</strong><br />Capture the impact of, and use metrics to support (if applicable), the innovative approach to programs and services as demonstrated by, but not limited to:
		<ul><li>Improved performance by doing things that may be unique, leading-edge, or new to the public service;</li>
		<li>Changes to the organizational culture or the traditional approach to management or problem solving; </li>
		<li>Demonstrates an experimental or innovative mindset whereby being open to change, taking calculated risks and challenge the status quo to try something new, resulted in a measurable outcome;</li>
		<li>Effect that the innovative approach to the programs or services has had on its intended internal or external stakeholders;</li>
		<li>Effect that the innovative approach to the programs orz services has had on the internal operations of the individuals, teams, or organizations delivering the programs or services;</li>
		<li>Quantitative or measurable improvement to the programs or services;</li>
		<li>Demonstrates why and how this was innovative.</li></ul>";
  $translations[2][6] = '';
  $translations[2][7] = '';
  $translations[2][8] = '';
  $translations[2][9] = '';

  /* Leadership */
  $translations[3][0] = 'In this section, provide a brief statement that summarizes or restates the main points of the nomination, submission or personal contribution.  The purpose of the summary is to give the adjudicators and judges a condensed and objective account of the main idea(s) and accomplishment(s) of the nomination.<br><br>
		<em>(Note that this section will be used by the Premier’s Awards team for communications purposes if this nomination is selected as a finalist.)</em>';
  $translations[3][1] = "To establish a background that will provide perspective to the work achieved, briefly describe the conditions under which the employee demonstrated exemplary leadership.";
  $translations[3][2] = "<strong>Complexity:</strong><br />Describe the nominee’s ability to demonstrate exemplary leadership acumen including, but not limited to:
	 	<ul><li>Size of the organization,  project, process, or initiative managed;</li>
		<li>Managing complex situations including: large-scale initiatives, managing and mitigating risks, creatively solving problems and implementing solutions;</li>
		<li>Constraints encountered and overcome under their leadership (i.e. time frame, technical, financial, organizational, policy, etc.).</li></ul>";
  $translations[3][4] = "<strong>Valuing People:</strong><br />Identify and describe how the employee has demonstrated their leadership in supporting the workplace either by leading a team or organization or as leader of a substantial project, process, or initiative. Considerations may include, but are not limited to:
		<ul><li>Ability to create, communicate, and implement a clear and compelling vision for their team and which aligns with the Corporate Plan for the BC Public Service;</li>
		<li>Ability to establish trust, motivate, and receive high satisfaction ratings from their employees and/or stakeholders; </li>
		<li>Ability to involve, empower, and lead staff through times of change;</li>
		<li>Demonstrates an investment in personal and organizational learning about trends and new ideas in their sector and the broader government context; Champions employee recognition, and collaborative team-based environments;</li>
		<li>Commitment to succession management though knowledge transfer and mentorship; </li>
		<li>Models the importance of respect, inclusion, ethics and integrity and ensure members are aware of their obligations with regards to ethics and professional conduct; </li>
		<li>Proven support for those that are willing to try something new, recognizing their intent and effort but accept failure by not casting blame, but rather learning from it, improving and moving forward.</li></ul>";
  $translations[3][5] = "<strong>Impact:</strong><br />Describe, and use metrics to support (where applicable), the effect that the leader has had on employees, clients, the public service, and/or citizens of British Columbia. Considerations may include, but are not limited to:
		<ul><li>Demonstrated improvement to the quality of the workplace for employees by contributing to the enhancement of diversity, health and safety, workplace culture and employee development; </li>
		<li>Demonstrated support for innovation, new technology, and best practices; that resulted in the improvement of workplace processes i.e.  reducing costs, increasing efficiencies, etc.</li>
		<li>Significantly improved the quality, cost-effectiveness, or productivity of services to internal or external stakeholders;</li>
		<li>Demonstrated improvement to the quality of the workplace for employees by contributing to the enhancement of </li>
		<li>Measurable benefits to either their organization(s) and/or the citizens of British Columbia through process improvements to transform business practices, and/or support sustainable revenue generation or savings;</li>
		<li>Significantly improved organizational performance as indicated by Work Environment Survey scores.</li></ul>";
  $translations[3][6] = "<strong>Commitment to the Organization:</strong><br />
		<ul><li>Anticipates future trends and works with others to develop strategies to meet future challenges;</li>
		<li>Exhibits ability to make decisions with considerations of the long-term impacts and context, anticipating not just the current need but also emerging priorities;</li>
		<li>Displays ability to demonstrate an experimental or innovative mindset whereby being open to change, taking calculated risks and challenging the status quo to try something new resulting in a measurable outcome;</li>
		<li>Enables innovation by visibly and actively inviting and advancing new ideas within their organization and demonstrates the courage to embrace change;</li>
		<li>Demonstrates aptitude for strong client service orientation by ensuring that service design needs are driven by citizens’ needs or client outcomes, rather than internally focused metrics.</li></ul>";
  $translations[3][7] = '';
  $translations[3][8] = '';
  $translations[3][9] = '';

  /* Organizational Excellence */
  $translations[4][0] = "In this section, provide a brief statement that summarizes or restates the main points of the nomination, submission or project.  The purpose of the summary is to give the adjudicators and judges a condensed and objective account of the main ideas and feature of the nomination.
    <em>(Note that this section will be used by the Premier’s Awards team for communications purposes if this nomination is selected as a finalist.)</em>';";
  $translations[4][1] = "To establish a background that will provide perspective to the work achieved, briefly describe why the new approach to the process, policy or service was undertaken.";
  $translations[4][2] = "<strong>Complexity:</strong><br />Describe the scope and scale of the delivery of the program, service, or initiative that resulted in substantial benefits to their organization, the public service  or citizens of British Columbia, including:
		<ul><li>Size of the program, service, or initiative;</li>
		<li>Risks encountered;</li>
		<li>Identify constraints which may include time frames, financial, policy, etc.;</li>
		<li>Identifies challenges around aligning stakeholder or partner group interests;</li>
		<li>Technical or organizational difficulties identified and addressed;</li></ul>";
  $translations[4][3] = "<strong>Approach:</strong><br />Identify key aspects of the approach taken in the delivery of the new program, service, or initiative that may include, but are not limited to:
		<ul><li>The use of a citizen-centric or customer-centric approach at the heart of the design and/or implementation of a policy/project;</li>
		<li>Support for innovation, risk taking, and a commitment to ongoing improvements by incorporating  or contributing to best practices;</li>
		<li>Removing barriers to overcome constraints;</li>
		<li>Change resilience – demonstration of strategies that support success even while going through change and transformation;</li>
		<li>Attention to cross-government processes critical for meeting stakeholder needs.</li></ul>";
  $translations[4][5] = "<strong>Impact:</strong><br />Describe, and use metrics to support, the outcomes that the program, service, or initiative has had on the organization, public service or citizens of British Columbia including, not limited to:
		<ul><li>Process improvements in business practices;</li>
		<li>Extent to which the outcomes and objectives have significantly improved government-to-business or government-to-citizen program or service delivery;</li>
		<li>Extent to which the outcomes and o bjectives significantly improved government-to-business or government-to-citizen service delivery;</li>
		<li>Increased client satisfaction to high quality service delivery;</li>
		<li>Measurable benefits to either their organization(s) and/or the citizens of British Columbia through process improvements to transform business practices, and/or support sustainable revenue generation or savings;</li>
		<li>Operational efficiencies as demonstrated by financial or other key performance indicators.</li></ul>";
  $translations[4][6] = "";
  $translations[4][7] = "";
  $translations[4][8] = "";
  $translations[4][9] = "";

	/* Partnership */
  $translations[5][0] = "In this section, provide a brief statement that summarizes or restates the main points of the nomination, project or partnership.  The purpose of the summary is to give the adjudicators and judges a condensed and objective account of the main idea(s) and accomplishment(s) of the nomination.<br><br>
		 <em>(Note that this section will be used by the Premier’s Awards team for communications purposes if this nomination is selected as a finalist.)</em><br>";
  $translations[5][1] = "To establish a background that will provide perspective to the work achieved, briefly describe why the partnership was undertaken.";
  $translations[5][2] = "<strong>Complexity:</strong><br />Describe the scope and scale of the joint-ventures or multi-party initiatives including, but not limited to:
		<ul><li>Size of the project, process, or initiative;</li>
		<li>Risks encountered;</li>
		<li>Constraints encountered and overcome (i.e. time frame, technical, financial, organizational, policy, etc.);</li>
		<li>Identify challenges around aligning stakeholder or partner group interests;</li>
		<li>Technical or organizational difficulties addressed;</li>";

  $translations[5][3] = "<strong>Approach:</strong><br />Identify key aspects of the approach taken in key aspects of the partnership including, but not limited to:
		<ul><li>Developing and managing sustained strategic partnerships with other government, private sector, volunteer or non-profit organizations that integrate policy and/or service delivery, with a view to better serving British Columbians;</li>
		<li>Building relationships with internal or external stakeholder(s) to achieve mutually beneficial goals or mandates;</li>
		<li>The use of a citizen-centric or customer-centric approach at the heart of the design and/or partnership;</li>
		<li>Creativity and/or use of new technology or methods (i.e. behavioural insights, service design) to achieve results;</li>
		<li>Risk and/or change management strategy;</li>
		<li>Application and/or development of best practices to remove barriers that may have prevented the successful outcome of the project;</li>
		<li>Demonstration of inclusive employee or citizen engagement practices with diverse stakeholder groups. </li></ul>";

  $translations[5][5] = "<strong>Impact:</strong><br />Describe, and use metrics to support (where applicable), the effect that the partnership has had on the organization, public service or citizens of British Columbia including, not limited to:
		<ul><li>Measurable benefits  to the organization(s) and/or the citizens of British Columbia through process improvements that transform business practices, and/or support sustainable revenue generation or savings;</li>
		<li>Effect on the community, internal or external stakeholders including any social, economic, and environmental benefits achieved as the result of the partnership;</li>
		<li>Extent to which the outcomes and objectives of the project, program or initiative were achieved;</li>
		<li>Effect that the partnership had on operational efficiencies as demonstrated by financial or other key performance indicators;</li>
		<li>Effect on the improved quality, cost-effectiveness, or productivity of services to internal and/or external stakeholders and/or the citizens of British Columbia;</li>
		<li>Extent to which the outcomes and objectives have significantly improved government-to-business or government-to-citizen program or service delivery.</li></ul>";
  $translations[5][6] = '';
  $translations[5][7] = '';
  $translations[5][8] = '';

	/* Legacy */
  $translations[6][0] = "In this section, provide a brief statement that that summarizes or restates the main points of the nomination, personal contribution or lasting legacy within the BC Public Service and/or the province of British Columbia.  The purpose of the summary is to give the adjudicators and judges a condensed and objective account of the main idea(s) and accomplishment(s) of the nomination.<br><br>
		<em>(Note that this section will be used by the Premier’s Awards team for communications purposes if this nomination is selected as a finalist.</em>)";
  $translations[6][1] = "To establish a background that will provide perspective to the work achieved, briefly describe the conditions under which the employee demonstrated their contribution to the BC Public Service including career highlights.";
  $translations[6][2] = "<strong>Complexity:</strong><br />Explain how the employee has demonstrated exemplary leadership throughout their career including, but not limited to:
		<ul><li>Ability to demonstrate superior leadership through complex situations including: large-scale initiatives; managing and mitigating risks; creatively solving problems and implementing solutions; </li>
		<li>Constraints encountered and overcome (i.e. time frame, technical, financial, organizational, policy, etc.);</li>
		<li>Application and/or development of best practices to remove barriers that may have prevented successful outcomes.</li></ul>";
  $translations[6][4] = "<strong>Valuing People:</strong><br />Identify and describe how the employee has demonstrated their leadership in supporting the workplace either by leading a team or organization or as leader of a substantial project, process, or initiative. Considerations may include, but are not limited to:
	<ul><li>Ability to create, communicate, and implement a clear and compelling vision for their team and which aligns with the Corporate Plan for the BC Public Service;</li>
    <li>Anticipates future trends and works with others to develop strategies to meet future challenges;</li>
    <li>Ability to establish trust, motivate, and receive high satisfaction ratings from their employees and/or stakeholders; </li>
    <li>Ability to involve, empower, and lead staff through times of change;</li>
    <li>Demonstrates an investment in personal and organizational learning about trends and new ideas in their sector and the broader government context;</li>
    <li>Commitment to succession management though knowledge transfer and mentorship; </li>
    <li>Models the importance of respect, inclusion, ethics and integrity and ensure members are aware of their obligations with regards to ethics and professional conduct.</li></ul>";
  $translations[6][5] = "<strong>Impact:</strong><br />Describe, and use metrics to support (where applicable), the ongoing positive contributions the individual has made to the BC Public Service and/or the province of British Columbia. Considerations may include, but are not limited to:
		<ul><li>Measurable benefits to either their organization(s) and/or the citizens of British Columbia;</li>
		<li>Impact the nominees’ career has had on the community, internal operations and/or external organizations including any social, economic, and environmental benefits achieved as the result of their body of work;</li>
		<li>Demonstrated improvement to the quality of the workplace for employees by contributing to the enhancement of diversity, health and safety, workplace culture and employee development;  </li>
		<li>Proven ability to demonstrate an experimental or innovative mindset whereby being open to change, taking calculated risks and challenging the status quo to try something new resulted in a measurable outcome;</li>
		<li>Significantly improved the quality, cost-effectiveness, or productivity of services to internal or external stakeholders;</li>
		<li>Significantly improved government-to-business or government-to-citizen service delivery;</li>
		<li>Provincial, national or global recognition for the contributions the nominee has made to the development of best practices in their field of expertise.</li></ul>";
  $translations[6][6] = '';
  $translations[6][7] = "<strong>Contribution to BC Public Service excellence:</strong><br />Describe how the individual approached leadership that resulted in public service excellence. Considerations include, but are not limited to:
		<ul><li>Outstanding dedication to their work  while maintaining a high level of commitment to BC Public Service values and government direction;</li>
		<li>Leads others in ways that embody the ideal vision of leadership within the BC Public Service; </li>
		<li>Exhibits ability to make decisions with considerations of the long-term impacts and context, anticipating not just the current need but also emerging priorities;</li>
		<li>Enables innovation by visibly and actively inviting and advancing new ideas within their organization and demonstrates the courage to embrace change;</li>
		<li>Facilitating, re-enforcing, and successfully leading through changes necessary to promote innovation, continuous improvement, or improved service delivery to internal or external clients;</li>
		<li>Demonstrates aptitude for strong client service orientation by ensuring that service design needs are driven by citizen’s needs or client outcomes rather than internally focused metrics;</li>
		<li>Demonstration of public service values throughout their career while continually developing their subject matter expertise;</li>
		<li>Demonstration of their commitment to diversity and inclusiveness in both the work environment and in the development of programs, policies and services.</li></ul>";
  $translations[6][8] = '';

	/* Emerging Leader */
  $translations[7][0] = "In this section, provide a brief statement that that summarizes or restates the main points of the nomination, submission or personal contribution.  The purpose of the summary is to give the adjudicators and judges a condensed and objective account of the main idea(s) and accomplishment(s) of the nomination.<br><br>
		<em>(Note that this section will be used by the Premier’s Awards team for communications purposes if this nomination is selected as a finalist.)</em>";
  $translations[7][1] = "To establish a background that will provide perspective to the work achieved, briefly describe the conditions under which the employee has demonstrated exemplary formal or informal leadership.";
  $translations[7][4] = "<strong>Valuing People:</strong><br />Identify and describe how the employee has demonstrated their leadership in supporting the workplace including, but not limited to:
		<ul><li>Ability to demonstrate leadership through innovative problem solving, team building and collaboration with colleagues at all levels of the organization;</li>
		<li>Actively enhancing the quality of the workplace through demonstrating a commitment to diversity and inclusiveness in both the work environment and in the development of programs, policies and services; </li>
		<li>Models integrity and a commitment to ethical conduct and decision making.</li></ul>";
  $translations[7][5] = "<strong>Impact:</strong><br />Describe, and use metrics to support (if applicable), how the employee exemplifies the future of corporate leadership as demonstrated through, but not limited to:
		<ul><li>The effect that the leader has had on employees, clients, the public service, and/or citizens of British Columbia. </li>
		<li>Demonstrated improvement to the quality of the workplace for employees by contributing to the enhancement of diversity, health and safety, workplace culture and employee development; </li>
		<li>Demonstrated support for innovation, new technology, and best practices; that resulted in the improvement of workplace processes i.e.  reducing costs, increasing efficiencies, safety, etc.</li>
		<li>Measurable benefits to either their organization(s) and/or the citizens of British Columbia through process improvements to transform business practices, and/or support sustainable revenue generation or savings.</li></ul>";
  $translations[7][6] = "<strong>Commitment to the Organization:</strong><br />Identify and describe how the employee has demonstrated their leadership in operations including, but not limited to:
		<ul><li>Demonstrates commitment to and pride in the BC Public Service by contributions that enhance its reputation;</li>
		<li>Proven thought-leader who can constructively articulate a strong case for change by challenging assumptions, timelines and recommendations to ensure that they are driven by citizens’ needs rather than administrative convenience;</li>
		<li>Demonstrates support for workplace innovation, new technology, and best practices by modelling a culture of curiosity, seeking out new knowledge, collaboration, encouraging dialogue and inviting competing ideas;</li>
		<li>Exhibits ability to make decisions with considerations of the long-term impacts and context, anticipating not just the current need but also emerging priorities;</li>
		<li>Demonstrates thoughtful risk management and ability to accept failure by learning from it, improving and moving forward;</li>
		<li>Demonstrates success through measurable project/program outcomes.</li></ul>";
  $translations[7][7] = "";
  $translations[7][8] = "";
  $translations[7][9] = "";

  /* Evidence-Based Design */
  $translations[8][0] = "In this section, provide a brief statement that that summarizes or restates the main points of the nomination, project or partnership.  The purpose of the summary is to give the adjudicators and judges a condensed and objective account of the main idea(s) and accomplishment(s) of the nomination.<br><br>
		<em>(Note that this section will be used by the Premier’s Awards team for communications purposes if this nomination is selected as a finalist.)</em>";
  $translations[8][1] = "To establish a background that will provide perspective to the work achieved, briefly describe why the policy or program was developed.";
  $translations[8][2] = "<strong>Complexity</strong><br />Describe the scope and scale of the evidence-based or evidence-informed approach to developing the policy or program including but not limited to:
		<ul><li>What necessitated the development of the policy or program? Describe the reason and evidence for the change or initiative;</li>
		<li>Risks encountered and overcome; </li>
		<li>Identify constraints which may include time frames, financial, existing policy, etc.;</li>
		<li>Identifies challenges around aligning stakeholder or partner group interests;</li>
		<li>Technical or organizational difficulties identified and addressed.</li></ul>";
  $translations[8][3] = "<strong>Approach</strong><br />Describe how the new policy or program used an evidence-based or evidence-informed approach for the development from inception to delivery including, but not limited to:
		<ul><li>The evidence-based or evidence-informed process in which the policy framework was designed;</li>
		<li>Demonstration of the policy cycle including clear problem identification, current state, best practices or leading edge and gap analysis, development and balanced analysis of options, evidence-based or evidence-informed decision making, implementation, evaluation;</li>
		<li>The use of foundational policy analysis tools to support recommendations (i.e. data and/or cost analysis, cross-jurisdictional and/or international reviews, peer reviewed research, stakeholder engagement etc.);</li>
		<li>The use of new technology or tools (i.e. Data Science, Service Design, etc. to support policy recommendations);</li>
		<li>Inclusive citizen engagement practices that reflects a diverse population within British Columbia.</li></ul>";
  $translations[8][4] = "";
  $translations[8][5] = "<strong>Impact</strong><br />Capture the impact of, and use metrics to support (if applicable), the evidence-based approach that resulted in the new policy or program as demonstrated by, but not limited to:
		<ul><li>Effect on the community, internal or external stakeholders including any social, economic, and environmental benefits achieved as the result of the policy or program;</li>
		<li>Extent to which the outcomes and objectives of the policy or program were achieved;</li>
		<li>Effect that the policy or program had on operational efficiencies as demonstrated by financial or other key performance indicators;</li>
		<li>Quantitative or measurable improvement to the programs or services;</li>
		<li>Application and/or development of best practices to remove barriers that may have prevented the successful outcome of the policy or program.</li></ul>";
  $translations[8][6] = "";
  $translations[8][7] = "";
  $translations[8][8] = "";
  $translations[8][9] = "";


  /* Regional Impact */
  $translations[9][0] = "In this section, provide a brief statement that summarizes or restates the main points of the nomination, submission or project, including a brief description of the town, city, or region. The purpose of the summary is to give the adjudicators and judges a condensed and objective account of the main idea(s) and accomplishment(s) of the nomination.<br><br>
		<em> (Note that this section will be used by the Premier’s Awards team for communications purposes if this nomination is selected as a finalist.)</em>";
  $translations[9][1] = "To establish a background that will provide perspective to the work achieved, briefly describe why the policy or program was developed.";
  $translations[9][2] = "<strong>Complexity</strong><br />Describe the scope and scale of the program, project or initiative that resulted in significant impact that directly benefited local citizens, including but not limited to:
		<ul>
		<li>Size of the program, service, or initiative;</li>
		<li>Risks encountered;</li>
		<li>Challenges around introducing a new approach to solve a problem;</li>
		<li>Constraints encountered and overcome, which may include timeframes, financial, policy, technical, etc.;</li>
		<li>Challenges around aligning stakeholder or partner group interests.</li>
		</ul>";
  $translations[9][3] = "<strong>Approach</strong><br />Describe key aspects of the approach taken throughout the development of the new program, project or initiative including, but not limited to:
		<ul>
		<li>The process used to generate innovative ideas, fresh perspectives, new opportunities, and creativity in the design;</li>
		<li>Application of a user-centric or citizen-centric approach in the development of the initiative/program;</li>
		<li>Adapting and refining the approach when things did not work well and learning from the setbacks/mistakes;</li>
		<li>Application and/or development of best practices to remove barriers that may have prevented the successful outcome of the project;</li>
		<li>Risk and/or change management strategy;</li>
		<li>Building relationships with external stakeholder(s) to achieve mutually beneficial goals or mandates;</li>
		<li>Demonstration of inclusive citizen engagement practices with diverse stakeholder groups.</li>
		</ul>";
  $translations[9][4] = "";
  $translations[9][5] = "<strong>Impact</strong><br />Describe, and use metrics to support (if applicable), the outcomes and impact that the program, project or initiative has had on the BC Public Service and local citizens including, but not limited to:
		<ul>
		<li>Demonstrate how an experimental or innovative mindset that was open to change, taking calculate risks, and challenging the status quo resulted in a measurable outcome;</li>
		<li>Extent to which the outcomes and objectives of the project, program or initiative were achieved;</li>
		<li>Quantitative or measurable improvement to the program, project or initiative;</li>
		<li>Efficiencies, improvements as demonstrated by financial or other key performance indicators;</li>
		<li>Effect on the community, internal or external stakeholders including any social, economic, and environmental benefits achieved;</li>
		<li>Effect that the impact has had on external stakeholders such as increased client satisfaction to high quality service delivery.</li>
		</ul>";
  $translations[9][6] = "";
  $translations[9][7] = "";
  $translations[9][8] = "";
  $translations[9][9] = "";

  return $translations;
}
