<?php

/**
 * Implements hook_form_FORM_ID_alter();
 */
function atwork_news_form_article_node_form_alter(&$form, &$form_state, $form_id) {

  $og_context = og_context();

  // hide un-needed form elements if this is a group news.
  if ($og_context) {
    if(!_atwork_is_admin()) {
      $form['field_additional_info']['#access'] = FALSE;
      $form['field_related_links']['#access'] = FALSE;
      $form['field_additional_info2']['#access'] = FALSE;
      $form['field_poll']['#access'] = FALSE;
      $form['field_snipet'][$form['language']['#value']][0]['value']['#default_value'] = 'Article';
      $form['field_snipet']['#access'] = FALSE;
      $form['og_group_ref']['#access'] = FALSE;
      $form['options']['status']['#default_value'] = 1;
      $form['options']['#access'] = TRUE;
      $form['actions']['delete']['#access'] = FALSE;
      drupal_add_css('#edit-body-und-0-format {display:none;}', $option['type'] = 'inline');
      // Hide exec tags, from globally available helper function.
      _atwork_hide_exec_tags($form);
    }
  } else {
    if (_atwork_is_admin()) {
      //If this is new and not an edit page.
      if ($form['nid']['#value'] === NULL) {
        // If the user is an editor and this is not in a group, default comments off.
        $form['#node']->comment = 0;
      }
    }
  }
}

/*
 * Implementation of hook_views_pre_render.
 *
 * Want to hide group content creation button for users who do not have proper permissions.
 *
 */
function atwork_news_views_pre_render(&$view) {

  if ($view->name == 'news' && $view->current_display == 'page_1') {
    global $user;
    // This is the associated group id.
    $gid = $view -> args[0];
    // Load the node and find user's roles.
    $roles = og_get_user_roles('node', $gid, $user->uid);

    // Hide the button link from anyone who does not have the requisite role to create this type of content.
    switch (TRUE) {
      case (in_array("Roving Reporter", $roles)):
      case (in_array("administrator", $roles)):
      default:
        drupal_add_css('.button {visibility: hidden;}', $option['type'] = 'inline');
        break;
    }
  }
}

/**
 * Implementation of hook_form_alter().
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function atwork_news_form_alter(&$form, &$form_state, $form_id){
  if ($form_id == 'article_node_form') {
    $form['options']['sticky']['#title'] = t('Top news story (sticky)');
    $form['options']['promote']['#title'] = t('Scrolling news (promoted)');
  }
}


/**
 * Implements hook_entity_view_alter().
 */
function atwork_news_entity_view_alter(&$build, $type) {
  if($type == 'node' && $build['#node']->nid == 46343 ) {
    drupal_add_js(drupal_get_path('module', 'atwork_news') . '/js/parralex_node.js');
  }
}
