<?php

function atwork_caching_node_presave($node) {
  _atwork_clear_view_cache($node);
}

function atwork_caching_node_delete($node) {
  _atwork_clear_view_cache($node);
}

function atwork_caching_comment_presave($comment) {
  require_once(drupal_get_path('module', 'cache_actions') . '/cache_actions.rules.inc');
  
  $cached_views = array(
    'home_page_blocks:comments' => 'home_page_blocks:comments',
    'recent_comments:page' => 'recent_comments:page',
  );
  cache_actions_action_clear_views_display_cache($cached_views);
}

function atwork_caching_comment_delete($comment) {
  require_once(drupal_get_path('module', 'cache_actions') . '/cache_actions.rules.inc');
  
  $cached_views = array(
    'home_page_blocks:comments' => 'home_page_blocks:comments',
    'recent_comments:page' => 'recent_comments:page',
  );
  cache_actions_action_clear_views_display_cache($cached_views);
}

function _atwork_clear_view_cache($node) {
  require_once(drupal_get_path('module', 'cache_actions') . '/cache_actions.rules.inc');
  
  $cached_views = array();
  
  switch ($node->type) {
    case 'blog':
      $cached_views['home_page_blocks:blogs'] = 'home_page_blocks:blogs';
      $cached_views['home_page_blocks:blogs_attach'] = 'home_page_blocks:blogs_attach';
      break;
    
    case 'forum':
      $cached_views['home_page_blocks:forums'] = 'home_page_blocks:forums';
      $cached_views['home_page_blocks:forums_attach'] = 'home_page_blocks:forums_attach';
      break;
    
    case 'article':
      $poll = field_get_items('node', $node, 'field_poll');
      $video = field_get_items('node', $node, 'field_video');
      
      if ($poll) {
        $cached_views['home_page_blocks:polls'] = 'home_page_blocks:polls';
        $cached_views['home_page_blocks:polls_attach'] = 'home_page_blocks:polls_attach';
        $cached_views['polls:page'] = 'polls:page';
      }
      
      if ($video) {
        $cached_views['home_page_blocks:videos'] = 'home_page_blocks:videos';
        $cached_views['home_page_blocks:videos_attach'] = 'home_page_blocks:videos_attach';
        $cached_views['videos:page'] = 'videos:page';
        $cached_views['videos:block_1'] = 'videos:block_1';
      }
      
      // top and scrolling news
      $cached_views['home_page_blocks:block_1'] = 'home_page_blocks:block_1';
      $cached_views['home_page_blocks:block_2'] = 'home_page_blocks:block_2';
      $cached_views['news:page'] = 'news:page';
      break;
      
    case 'wiki':
      $cached_views['home_page_blocks:wikis'] = 'home_page_blocks:wikis';
      $cached_views['wiki_categories:block'] = 'wiki_categories:block';
      $cached_views['wiki_categories:block_1'] = 'wiki_categories:block_1';
      break;
    
    case 'ecard':
      $cached_views['e_cards:page'] = 'e_cards:page';
      $cached_views['e_cards:block_1'] = 'e_cards:block_1';
      $cached_views['e_cards:block_2'] = 'e_cards:block_2';
      $cached_views['e_cards_categories:block_1'] = 'e_cards_categories:block_1';
      break;
    
    case 'event':
      $cached_views['home_page_blocks:events'] = 'home_page_blocks:events';
      break;
  }
  
  if ($cached_views) {
    cache_actions_action_clear_views_display_cache($cached_views);
  }
}