<?php

/*
 * Implementation of hook_menu()
 * 
 * Provide a starting point for our reporting section
 */
function atwork_reporting_menu() {
  $items['reports'] = array(
    'title' => 'Atwork Reports', 
    'page callback' => 'atwork_reporting_page',
    'access arguments' => array('access atwork reports'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['reports/view'] = array(
    'title' => 'Atwork Reports',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('access atwork reports'),
  );
  
  return $items;
}

/*
 * Page callback for reports
 */
function atwork_reporting_page() {
  return t('');
}

/*
 * Implementation of hook_permissions
 */
function atwork_reporting_permission() {
  return array(
    'access atwork reports' => array(
      'title' => t('Access Atwork Reports'),
      'description' => t('View comments/ecards/likes by date, distributions, etc.'),
    ),
  );
}

/**
 * Implements hook_view_pre_render()
 * 
 * For each reporting view we provide a nice-looking summary as well as a table
 * of all raw results
 */
function atwork_reporting_views_pre_render(&$view) {
//dpm($view);
  if ($view->name == 'comments_admin' && $view->current_display == 'page_2') {
    if (isset($view->result[0]->comment_created_day)) {
      $date_start = $view->result[0]->comment_created_day;
      $last_result = end($view->result);
      $date_end = $last_result->comment_created_day;
      $new_results = array();

      $i = $date_start;
      $processing = TRUE;
      while ($processing) {
        $day_found = FALSE;
        foreach($view->result as $key => $result) {
          if ($result->comment_created_day == $i) {
            $day_found = TRUE;
            break;
          }
        }

        if ($day_found) {
          $new_results[] = $result;
        }
        else {
          $new_result = array(
            'cid' => 0,
            'comment_created' => date('D, M j, Y', strtotime($i)),
            'comment_created_day' => $i,
          );

          $new_results[] = (object) $new_result;

        }

        if ($i == $date_end) {
          $processing = FALSE;
        }

        // increment by one day
        $i = date("Ymd", mktime(0, 0, 0, date('m', strtotime($i)), (date('d', strtotime($i)) + 1), date('Y', strtotime($i))));

      }

      $view->result = $new_results;
      
      $total_count = 0;
      $weekend_days = 0;
      foreach ($new_results as $result) {
        $total_count = $total_count + $result->cid;
        $week_day = date('w', strtotime($result->comment_created_day));
        if ($week_day == 0 || $week_day == 6) {
          $weekend_days++;
        }
      }
      
      $date_start = date('F j, Y', strtotime($date_start));
      $date_end = date('F j, Y', strtotime($date_end));
      $average = number_format(($total_count / count($new_results)), 2);
      $average_weekdays = number_format(($total_count / (count($new_results) - $weekend_days)), 2);
      
      $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_start to $date_end</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total Comments:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Average comments per day:&nbsp;</div>
      <div class="field-items">$average</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Average comments per business day:&nbsp;</div>
      <div class="field-items">$average_weekdays</div>
    </div>
  </div>
</div>
EOT;
      
      // raw data
      $header = array(
        t('Date'),
        t('Number of comments'),
      );
      
      $rows = array();
      foreach ($new_results as $result) {
        $rows[] = array(
          'date' => date('l, F j, Y', strtotime($result->comment_created_day)),
          'count' => $result->cid,
        );
      }
      
      $variables = array(
        'header' => $header,
        'rows' => $rows,
        'attributes' => array(),
        'caption' => '',
        'colgroups' => array(),
        'sticky' => FALSE,
        'empty' => '',
      );
      
      $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);

    }
  
  }
  
  if ($view->name == 'reports' && $view->current_display == 'page') {
    if (isset($view->result[0]->node_created_day)) {
      $date_start = $view->result[0]->node_created_day;
      $last_result = end($view->result);
      $date_end = $last_result->node_created_day;
      $new_results = array();

      $i = $date_start;
      $processing = TRUE;
      while ($processing) {
        $day_found = FALSE;
        foreach($view->result as $key => $result) {
          if ($result->node_created_day == $i) {
            $day_found = TRUE;
            break;
          }
        }

        if ($day_found) {
          $new_results[] = $result;
        }
        else {
          $new_result = array(
            'nid' => 0,
            'node_created' => date('D, M j, Y', strtotime($i)),
            'node_created_day' => $i,
          );

          $new_results[] = (object) $new_result;

        }

        if ($i == $date_end) {
          $processing = FALSE;
        }

        // increment by one day
        $i = date("Ymd", mktime(0, 0, 0, date('m', strtotime($i)), (date('d', strtotime($i)) + 1), date('Y', strtotime($i))));

      }

      $view->result = $new_results;
      
      $total_count = 0;
      $weekend_days = 0;
      foreach ($new_results as $result) {
        $total_count = $total_count + $result->nid;
        $week_day = date('w', strtotime($result->node_created_day));
        if ($week_day == 0 || $week_day == 6) {
          $weekend_days++;
        }
      }
      
      $date_start = date('F j, Y', strtotime($date_start));
      $date_end = date('F j, Y', strtotime($date_end));
      $average = number_format(($total_count / count($new_results)), 2);
      $average_weekdays = number_format(($total_count / (count($new_results) - $weekend_days)), 2);
      
      $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_start to $date_end</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total Posts:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Average posts per day:&nbsp;</div>
      <div class="field-items">$average</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Average posts per business day:&nbsp;</div>
      <div class="field-items">$average_weekdays</div>
    </div>
  </div>
</div>
EOT;
      
      // raw data
      $header = array(
        t('Date'),
        t('Number of comments'),
      );
      
      $rows = array();
      foreach ($new_results as $result) {
        $rows[] = array(
          'date' => date('l, F j, Y', strtotime($result->node_created_day)),
          'count' => $result->nid,
        );
      }
      
      $variables = array(
        'header' => $header,
        'rows' => $rows,
        'attributes' => array(),
        'caption' => '',
        'colgroups' => array(),
        'sticky' => FALSE,
        'empty' => '',
      );
      
      $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);
    }
  }
  
  if ($view->name == 'reports' && $view->current_display == 'page_3') {
    if (isset($view->result[0]->node_created_day)) {
      $date_start = $view->result[0]->node_created_day;
      $last_result = end($view->result);
      $date_end = $last_result->node_created_day;
      $new_results = array();

      $i = $date_start;
      $processing = TRUE;
      while ($processing) {
        $day_found = FALSE;
        foreach($view->result as $key => $result) {
          if ($result->node_created_day == $i) {
            $day_found = TRUE;
            break;
          }
        }

        if ($day_found) {
          $new_results[] = $result;
        }
        else {
          $new_result = array(
            'votingapi_vote_node_timestamp' => 0,
            'node_created' => date('D, M j, Y', strtotime($i)),
            'node_created_day' => $i,
          );

          $new_results[] = (object) $new_result;

        }

        if ($i == $date_end) {
          $processing = FALSE;
        }

        // increment by one day
        $i = date("Ymd", mktime(0, 0, 0, date('m', strtotime($i)), (date('d', strtotime($i)) + 1), date('Y', strtotime($i))));

      }

      $view->result = $new_results;
      
      $total_count = 0;
      $weekend_days = 0;
      foreach ($new_results as $result) {
        $total_count = $total_count + $result->votingapi_vote_node_timestamp;
        $week_day = date('w', strtotime($result->node_created_day));
        if ($week_day == 0 || $week_day == 6) {
          $weekend_days++;
        }
      }
      
      $date_start = date('F j, Y', strtotime($date_start));
      $date_end = date('F j, Y', strtotime($date_end));
      $average = number_format(($total_count / count($new_results)), 2);
      $average_weekdays = number_format(($total_count / (count($new_results) - $weekend_days)), 2);
      
      $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_start to $date_end</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total Likes:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Average likes per day:&nbsp;</div>
      <div class="field-items">$average</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Average likes per business day:&nbsp;</div>
      <div class="field-items">$average_weekdays</div>
    </div>
  </div>
</div>
EOT;
      
      // raw data
      $header = array(
        t('Date'),
        t('Number of likes'),
      );
      
      $rows = array();
      foreach ($new_results as $result) {
        $rows[] = array(
          'date' => date('l, F j, Y', strtotime($result->node_created_day)),
          'count' => $result->votingapi_vote_node_timestamp,
        );
      }
      
      $variables = array(
        'header' => $header,
        'rows' => $rows,
        'attributes' => array(),
        'caption' => '',
        'colgroups' => array(),
        'sticky' => FALSE,
        'empty' => '',
      );
      
      $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);
    }
  }
  
  if ($view->name == 'reports' && $view->current_display == 'page_1') {
    if (!$view->result) {
      return;
    }
    if ($view->exposed_data['created']['min'] && $view->exposed_data['created']['max']) {
      $date_span = date('F j, Y', strtotime($view->exposed_data['created']['min'])) 
        . ' ' . t('to') . ' ' .
        date('F j, Y', strtotime($view->exposed_data['created']['max']));
    }
    else {
      $date_span = t('All time');
    }
    
    $total_count = 0;
    foreach ($view->result as $result) {
      $total_count = $total_count + $result->nid;
    }
    
          $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_span</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total Nodes:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
  </div>
</div>
EOT;
    
    
    // raw data
    $header = array(
      t('Content Type'),
      t('Number of nodes'),
    );
    
    $rows = array();
    foreach ($view->result as $result) {
      $rows[] = array(
        'hour' => $result->node_type,
        'count' => $result->nid,
      );
    }

    $variables = array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'caption' => '',
      'colgroups' => array(),
      'sticky' => FALSE,
      'empty' => '',
    );

    $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);
  
  }
  
  if ($view->name == 'reports' && $view->current_display == 'page_2') {
    if (!$view->result) {
      return;
    }
    if ($view->exposed_data['created']['min'] && $view->exposed_data['created']['max']) {
      $date_span = date('F j, Y', strtotime($view->exposed_data['created']['min'])) 
        . ' ' . t('to') . ' ' .
        date('F j, Y', strtotime($view->exposed_data['created']['max']));
    }
    else {
      $date_span = t('All time');
    }
    
    $total_count = 0;
    foreach ($view->result as $result) {
      $total_count = $total_count + $result->nid;
    }
    
          $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_span</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total Nodes:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
  </div>
</div>
EOT;
    
    
    // raw data
    $header = array(
      t('Tag'),
      t('Number of nodes'),
    );
    
    $rows = array();
    foreach ($view->result as $result) {
      $rows[] = array(
        'hour' => l($result->taxonomy_term_data_field_data_field_tags_name, 'taxonomy/term/' . $result->taxonomy_term_data_field_data_field_tags_tid),
        'count' => $result->nid,
      );
    }

    $variables = array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'caption' => '',
      'colgroups' => array(),
      'sticky' => FALSE,
      'empty' => '',
    );

    $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);
  
  }
  
  
  
  if ($view->name == 'comments_admin' && $view->current_display == 'page_5') {
    if (isset($view->result[0]->comment_created_day)) {
      $date_start = $view->result[0]->comment_created_day;
      $last_result = end($view->result);
      $date_end = $last_result->comment_created_day;
      $new_results = array();

      $i = $date_start;
      $processing = TRUE;
      while ($processing) {
        $day_found = FALSE;
        foreach($view->result as $key => $result) {
          if ($result->comment_created_day == $i) {
            $day_found = TRUE;
            break;
          }
        }

        if ($day_found) {
          $new_results[] = $result;
        }
        else {
          $new_result = array(
            'votingapi_vote_comment_uid' => 0,
            'comment_created' => date('D, M j, Y', strtotime($i)),
            'comment_created_day' => $i,
          );

          $new_results[] = (object) $new_result;

        }

        if ($i == $date_end) {
          $processing = FALSE;
        }

        // increment by one day
        $i = date("Ymd", mktime(0, 0, 0, date('m', strtotime($i)), (date('d', strtotime($i)) + 1), date('Y', strtotime($i))));

      }

      $view->result = $new_results;
      
      $total_count = 0;
      $weekend_days = 0;
      foreach ($new_results as $result) {
        $total_count = $total_count + $result->votingapi_vote_comment_uid;
        $week_day = date('w', strtotime($result->comment_created_day));
        if ($week_day == 0 || $week_day == 6) {
          $weekend_days++;
        }
      }
      
      $date_start = date('F j, Y', strtotime($date_start));
      $date_end = date('F j, Y', strtotime($date_end));
      $average = number_format(($total_count / count($new_results)), 2);
      $average_weekdays = number_format(($total_count / (count($new_results) - $weekend_days)), 2);
      
      $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_start to $date_end</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total Likes:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Average likes per day:&nbsp;</div>
      <div class="field-items">$average</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Average likes per business day:&nbsp;</div>
      <div class="field-items">$average_weekdays</div>
    </div>
  </div>
</div>
EOT;
      
      // raw data
      $header = array(
        t('Date'),
        t('Number of likes'),
      );
      
      $rows = array();
      foreach ($new_results as $result) {
        $rows[] = array(
          'date' => date('l, F j, Y', strtotime($result->comment_created_day)),
          'count' => $result->votingapi_vote_comment_uid,
        );
      }
      
      $variables = array(
        'header' => $header,
        'rows' => $rows,
        'attributes' => array(),
        'caption' => '',
        'colgroups' => array(),
        'sticky' => FALSE,
        'empty' => '',
      );
      
      $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);

    }
  }
  
  if ($view->name == 'comments_admin' && $view->current_display == 'page_4') {
    if (!$view->result) {
      return;
    }
    if ($view->exposed_data['created']['min'] && $view->exposed_data['created']['max']) {
      $date_span = date('F j, Y', strtotime($view->exposed_data['created']['min'])) 
        . ' ' . t('to') . ' ' .
        date('F j, Y', strtotime($view->exposed_data['created']['max']));
    }
    else {
      $date_span = t('All time');
    }
    
    $total_count = 0;
    foreach ($view->result as $result) {
      $total_count = $total_count + $result->cid;
    }
    
          $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_span</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total Comments:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
  </div>
</div>
EOT;
    
    // rebuild results to show hours with no comments
    $new_results = array();
    for ($i=0; $i<24; $i++) {
      $hour_found = FALSE;
      foreach ($view->result as $key => $result) {
        if ($result->comment_created == $i) {
          $new_results[] = $view->result[$key];
          $hour_found = TRUE;
        }
      }
      if (!$hour_found) {
        $new_result = array(
          'cid' => 0,
          'comment_created' => sprintf("%02d", $i),
        );

        $new_results[] = (object) $new_result;
      }
    }
    
    $view->result = $new_results;
    
    // raw data
    $header = array(
      t('Hour'),
      t('Number of comments'),
    );
    
    $rows = array();
    foreach ($view->result as $result) {
      $rows[] = array(
        'hour' => $result->comment_created,
        'count' => $result->cid,
      );
    }

    $variables = array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'caption' => '',
      'colgroups' => array(),
      'sticky' => FALSE,
      'empty' => '',
    );

    $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);
  }
  
  if ($view->name == 'comments_admin' && $view->current_display == 'page_3') {
    if (!$view->result) {
      return;
    }
    if ($view->exposed_data['created']['min'] && $view->exposed_data['created']['max']) {
      $date_span = date('F j, Y', strtotime($view->exposed_data['created']['min'])) 
        . ' ' . t('to') . ' ' .
        date('F j, Y', strtotime($view->exposed_data['created']['max']));
    }
    else {
      $date_span = t('All time');
    }
    
    $total_count = 0;
    foreach ($view->result as $result) {
      $total_count = $total_count + $result->cid;
    }
    
          $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_span</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total Comments:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
  </div>
</div>
EOT;
    
    
    // raw data
    $header = array(
      t('Content Type'),
      t('Number of comments'),
    );
    
    $content_type_names = node_type_get_names();
    
    $rows = array();
    foreach ($view->result as $result) {
      $rows[] = array(
        'type' => $content_type_names[$result->node_comment_type],
        'count' => $result->cid,
      );
    }

    $variables = array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'caption' => '',
      'colgroups' => array(),
      'sticky' => FALSE,
      'empty' => '',
    );

    $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);
  }
  
  if ($view->name == 'ecard_reports' && $view->current_display == 'page') {
    if (isset($view->result[0]->ecard_timestamp_day)) {
      $date_start = $view->result[0]->ecard_timestamp_day;
      $last_result = end($view->result);
      $date_end = $last_result->ecard_timestamp_day;
      $new_results = array();

      $i = $date_start;
      $processing = TRUE;
      while ($processing) {
        $day_found = FALSE;
        foreach($view->result as $key => $result) {
          if ($result->ecard_timestamp_day == $i) {
            $day_found = TRUE;
            break;
          }
        }

        if ($day_found) {
          $new_results[] = $result;
        }
        else {
          $new_result = array(
            'hash' => 0,
            'ecard_timestamp' => date('D, M j, Y', strtotime($i)),
            'ecard_timestamp_day' => $i,
          );

          $new_results[] = (object) $new_result;

        }

        if ($i == $date_end) {
          $processing = FALSE;
        }

        // increment by one day
        $i = date("Ymd", mktime(0, 0, 0, date('m', strtotime($i)), (date('d', strtotime($i)) + 1), date('Y', strtotime($i))));

      }

      $view->result = $new_results;
      
      $total_count = 0;
      $weekend_days = 0;
      foreach ($new_results as $result) {
        $total_count = $total_count + $result->hash;
        $week_day = date('w', strtotime($result->ecard_timestamp_day));
        if ($week_day == 0 || $week_day == 6) {
          $weekend_days++;
        }
      }
      
      $date_start = date('F j, Y', strtotime($date_start));
      $date_end = date('F j, Y', strtotime($date_end));
      $average = number_format(($total_count / count($new_results)), 2);
      $average_weekdays = number_format(($total_count / (count($new_results) - $weekend_days)), 2);
      
      $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_start to $date_end</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total ecards:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Average ecards per day:&nbsp;</div>
      <div class="field-items">$average</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Average ecards per business day:&nbsp;</div>
      <div class="field-items">$average_weekdays</div>
    </div>
  </div>
</div>
EOT;
      
      // raw data
      $header = array(
        t('Date'),
        t('Number of ecards'),
      );
      
      $rows = array();
      foreach ($new_results as $result) {
        $rows[] = array(
          'date' => date('l, F j, Y', strtotime($result->ecard_timestamp_day)),
          'count' => $result->hash,
        );
      }
      
      $variables = array(
        'header' => $header,
        'rows' => $rows,
        'attributes' => array(),
        'caption' => '',
        'colgroups' => array(),
        'sticky' => FALSE,
        'empty' => '',
      );
      
      $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);
    }
  }
  
  if ($view->name == 'ecard_reports' && $view->current_display == 'page_1') {
    if (!$view->result) {
      return;
    }
    if ($view->exposed_data['created']['min'] && $view->exposed_data['created']['max']) {
      $date_span = date('F j, Y', strtotime($view->exposed_data['created']['min'])) 
        . ' ' . t('to') . ' ' .
        date('F j, Y', strtotime($view->exposed_data['created']['max']));
    }
    else {
      $date_span = t('All time');
    }
    
    $total_count = 0;
    foreach ($view->result as $result) {
      $total_count = $total_count + $result->hash;
    }
    
          $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_span</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total Ecards Sent:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
  </div>
</div>
EOT;
    
    
    // raw data
    $header = array(
      t('Category'),
      t('Number of ecards'),
    );
    
    $content_type_names = node_type_get_names();
    
    $rows = array();
    foreach ($view->result as $result) {
      $rows[] = array(
        'category' => $result->taxonomy_term_data_field_data_field_ecard_category_name,
        'count' => $result->hash,
      );
    }

    $variables = array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'caption' => '',
      'colgroups' => array(),
      'sticky' => FALSE,
      'empty' => '',
    );

    $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);
  }
  
  if ($view->name == 'comments_admin' && $view->current_display == 'page_6') {
    if (!$view->result) {
      return;
    }
    //dpm($view);
    
    if ($view->exposed_data['created']['min'] && $view->exposed_data['created']['max']) {
      $date_span = date('F j, Y', strtotime($view->exposed_data['created']['min'])) 
        . ' ' . t('to') . ' ' .
        date('F j, Y', strtotime($view->exposed_data['created']['max']));
    }
    else {
      $date_span = t('All time');
    }
    
    $total_count = 0;
    foreach ($view->result as $key => $result) {
      if (!$result->users_comment__field_data_field_gal_city_field_gal_city_valu) {
        $view->result[$key]->users_comment__field_data_field_gal_city_field_gal_city_valu = t('Unknown');
        $view->result[$key]->field_field_gal_city[0] = array(
          'rendered' => array(
            '#markup' => t('Unknown'),
            '#access' => TRUE,
          ),
          'raw' => array(
            'value' => t('Unknown'),
          ),
        );
        
        //$view->style_plugin->view->result[$key]->users_comment__field_data_field_gal_city_field_gal_city_valu = t('Unknown');
      }
      $total_count = $total_count + $result->cid;
    }
    //dpm($view->result);
    
          $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_span</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total Comments:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
  </div>
</div>
EOT;
    
    
    // raw data
    $header = array(
      t('City'),
      t('Number of comments'),
    );
    
    $rows = array();
    foreach ($view->result as $result) {
      $rows[] = array(
        'city' => $result->users_comment__field_data_field_gal_city_field_gal_city_valu,
        'count' => $result->cid,
      );
    }

    $variables = array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'caption' => '',
      'colgroups' => array(),
      'sticky' => FALSE,
      'empty' => '',
    );

    $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);
  }
  
  
  
  
  
  
  
  
  if ($view->name == 'comments_admin' && $view->current_display == 'page_7') {
    if (!$view->result) {
      return;
    }
    //dpm($view);
    
    
    if ($view->exposed_data['created']['min'] && $view->exposed_data['created']['max']) {
      $date_span = date('F j, Y', strtotime($view->exposed_data['created']['min'])) 
        . ' ' . t('to') . ' ' .
        date('F j, Y', strtotime($view->exposed_data['created']['max']));
    }
    else {
      $date_span = t('All time');
    }
    
    $total_count = 0;
    foreach ($view->result as $key => $result) {
      if (!$result->users_comment__field_data_field_gal_ministry_name_field_gal_) {
        $view->result[$key]->users_comment__field_data_field_gal_ministry_name_field_gal_ = t('Unknown');
        $view->result[$key]->field_field_gal_ministry_name[0] = array(
          'rendered' => array(
            '#markup' => t('Unknown'),
            '#access' => TRUE,
          ),
          'raw' => array(
            'value' => t('Unknown'),
          ),
        );
        
      }
      $total_count = $total_count + $result->cid;
    }
    //dpm($view->result);
    
          $view->attachment_after = <<<EOT
<div class="report-summary">
  <h3 class="report-title">Report Details</h3>
  <div class="content">
    <div class="field clearfix">
      <div class="field-label">Date Span:&nbsp;</div>
      <div class="field-items">$date_span</div>
    </div>
    <div class="field field-label-inline clearfix">
      <div class="field-label">Total Comments:&nbsp;</div>
      <div class="field-items">$total_count</div>
    </div>
  </div>
</div>
EOT;
    
    
    // raw data
    $header = array(
      t('Ministry'),
      t('Number of comments'),
    );
    
    $rows = array();
    foreach ($view->result as $result) {
      $rows[] = array(
        'city' => $result->users_comment__field_data_field_gal_ministry_name_field_gal_,
        'count' => $result->cid,
      );
    }

    $variables = array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array(),
      'caption' => '',
      'colgroups' => array(),
      'sticky' => FALSE,
      'empty' => '',
    );
    
    //dpm($view);
    $view->attachment_after .= '<h3 class="report-raw-data">Raw Data</h3>' . theme_table($variables);
  }
}

/*
 * Implementation of hook_form_alter()
 * 
 * Get rid of/change labels on the exposed filters
 */
function atwork_reporting_form_alter(&$form, &$form_state, $form_id) {
  //dpm($form);
  if ($form['#id'] == 'views-exposed-form-comments-admin-page-2'
       || $form['#id'] == 'views-exposed-form-comments-admin-page-3'
       || $form['#id'] == 'views-exposed-form-comments-admin-page-4'
       || $form['#id'] == 'views-exposed-form-comments-admin-page-5'
       || $form['#id'] == 'views-exposed-form-comments-admin-page-6'
       || $form['#id'] == 'views-exposed-form-comments-admin-page-7'
       || $form['#id'] == 'views-exposed-form-reports-page'
       || $form['#id'] == 'views-exposed-form-reports-page-1'
       || $form['#id'] == 'views-exposed-form-reports-page-2'
       || $form['#id'] == 'views-exposed-form-reports-page-3'
       || $form['#id'] == 'views-exposed-form-ecard-reports-page'
       || $form['#id'] == 'views-exposed-form-ecard-reports-page-1') {
    
    if (isset($form['#info']['filter-created']['label'])) {
      $form['#info']['filter-created']['label'] = '';
    }
    if (isset($form['#info']['filter-timestamp']['label'])) {
      $form['#info']['filter-timestamp']['label'] = '';
    }
    
    $form['created']['min']['#title'] = t('Start Date');
    $form['created']['max']['#title'] = t('End Date');
    $form['created']['min']['#type'] = 'date_popup';
    $form['created']['max']['#type'] = 'date_popup';
    $form['created']['min']['#date_format'] = 'Y-m-d';
    $form['created']['max']['#date_format'] = 'Y-m-d';
  }
}

/*
 * Implementation of hook_element_info_alter()
 * 
 * Do some special formatting of date_popup
 */
function atwork_reporting_element_info_alter(&$type) {
  if (isset($type['date_popup'])) {
    $type['date_popup']['#process'][] = 'atwork_reporting_date_popup_process';
  }
}

/*
 * Process callback for date_popup
 * 
 * Hide some labels and change the default dates
 */
function atwork_reporting_date_popup_process($element, $form_state, $complete_form) {
  if ($complete_form['#id'] == 'views-exposed-form-comments-admin-page-2'
       || $complete_form['#id'] == 'views-exposed-form-comments-admin-page-3'
       || $complete_form['#id'] == 'views-exposed-form-comments-admin-page-4'
       || $complete_form['#id'] == 'views-exposed-form-comments-admin-page-5'
       || $complete_form['#id'] == 'views-exposed-form-comments-admin-page-6'
       || $complete_form['#id'] == 'views-exposed-form-comments-admin-page-7'
       || $complete_form['#id'] == 'views-exposed-form-reports-page'
       || $complete_form['#id'] == 'views-exposed-form-reports-page-1'
       || $complete_form['#id'] == 'views-exposed-form-reports-page-2'
       || $complete_form['#id'] == 'views-exposed-form-reports-page-3'
       || $complete_form['#id'] == 'views-exposed-form-ecard-reports-page'
       || $complete_form['#id'] == 'views-exposed-form-ecard-reports-page-1') {
    $element['date']['#description'] = '';
    $element['date']['#title'] = '';
    $element['time']['#description'] = '';
    $element['time']['#title'] = '';
    
    // set default date
    if (!$element['#value']['date'] && !$element['date']['#default_value'] && !isset($_GET['created'])) {
      if ($element['#name'] == 'created[min]') {
        $element['#value']['date'] = date('Y-m-d', mktime(0, 0, 0, (date('n') - 1), 1, date('Y')));
        $element['date']['#default_value'] = date('Y-m-d', mktime(0, 0, 0, (date('n') - 1), 1, date('Y')));
        $element['date']['#value'] = date('Y-m-d', mktime(0, 0, 0, (date('n') - 1), 1, date('Y')));
      }
      if ($element['#name'] == 'created[max]') {
        $element['#value']['date'] = date('Y-m-d', mktime(0, 0, 0, date('n'), 1, date('Y')));
        $element['date']['#default_value'] = date('Y-m-d', mktime(0, 0, 0, date('n'), 1, date('Y')));
        $element['date']['#value'] = date('Y-m-d', mktime(0, 0, 0, date('n'), 1, date('Y')));
        $element['date']['#description'] = t('Defaulted to last month.');
      }
    }
  }

  return $element;
}

/*
 * Implementation of hook_views_query_alter()
 * 
 * Special case with ecards because if the sender and receiver are 
 * the same it shouldn't really count as an ecard
 */
function atwork_reporting_views_query_alter(&$view, &$query) {
  if ($view->name == 'ecard_reports') {
    $query->where[1]['conditions'][] = array(
      'field' => 'ecard.mail_from != ecard.mail_to',
      'value' => array(),
      'operator' => 'formula',
    );
  }
  if ($view->name == 'ecard_reports' && $view->current_display == 'page_1') {
    $query->table_queue['node_ecard']['join']->left_field = 'entity_id';
  }
}