<?php

/*
 * Implementation of hook_query_alter()
 *
 * Don't allow field_exclude_from_search to be shown on search
 */
function atwork_search_query_alter(&$query) {
  $is_search = FALSE;
  foreach ($query->getTables() as $table) {
    if ($table['table'] == 'search_index') {
      $is_search = TRUE;
    }
  }

  // disable on views
  if (isset($query->alterTags['views'])) {
    $is_search = FALSE;
  }

  if ($is_search) {
    $tables = $query->getTables();
    if (isset($tables['i']['table'])
      && isset($tables['n']['table'])
      && $tables['i']['table'] == 'search_index'
      && $tables['n']['table'] == 'node') {

      $or = db_or()->condition('efs.field_exclude_from_search_value', 0)->isNull('efs.field_exclude_from_search_value');

      $query->leftJoin('field_data_field_exclude_from_search', 'efs', '(efs.entity_id = n.nid)');
      $query->condition($or);
      $query->condition('n.type', 'multichoice', '<>');
      $query->condition('n.type', 'truefalse', '<>');
      $query->condition('n.type', 'poll', '<>');
      $query->condition('n.type', 'lsa_application', '<>');
      $query->condition('n.type', 'lsa_pin_application', '<>');
      $query->condition('n.type', 'wiki', '<>');
    }
  }
}

/*
 * Implementation of hook_form_alter()
 *
 * Edit the advanced search form
 *
 * Remove label from search block
 */
function atwork_search_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_form') {
    if (isset($form['advanced'])) {
      unset($form['advanced']['type']['#options']['page']);
      unset($form['advanced']['type']['#options']['multichoice']);
      unset($form['advanced']['type']['#options']['poll']);
      //unset($form['advanced']['type']['#options']['section']);
      //unset($form['advanced']['type']['#options']['section_page']);
      unset($form['advanced']['type']['#options']['truefalse']);
      unset($form['advanced']['type']['#options']['webform']);
      unset($form['advanced']['type']['#options']['lsa_application']);
      unset($form['advanced']['type']['#options']['image']);
      unset($form['advanced']['type']['#options']['lsa_pin_application']);
      //unset($form['advanced']['type']['#options']['gallery']);

      if(isset($form['advanced']['type']['#options']['classified'])){
        $form['advanced']['type']['#options']['classified'] = 'Classified ad';
      }
      if(isset($form['advanced']['type']['#options']['forum'])){
        $form['advanced']['type']['#options']['forum'] = 'Forum topic';
      }
      if(isset($form['advanced']['type']['#options']['section_page'])){
        $form['advanced']['type']['#options']['section_page'] = 'Page';
      }
      if(isset($form['advanced']['type']['#options']['question'])){
        $form['advanced']['type']['#options']['question'] = 'Q & A';
      }
    }
  }
  if ($form_id == 'search_block_form') {
    $form['actions']['submit']['#type'] = 'image_button';
    $form['search_block_form']['#suffix'] = _atwork_fa('search', 'style="cursor: pointer;" onclick="document.getElementById(\'search-block-form\').submit()"');
    $form['actions']['submit']['#value'] = '';
  }


  if ($form_id == 'custom_search_blocks_form_1') {

    $form['advanced_search'] = array(
      '#type' => 'fieldset',
      '#title' => t('Advanced search'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );

    if (isset($form['custom_search_criteria_or'])) {
      $form['advanced_search']['custom_search_criteria_or'] = $form['custom_search_criteria_or'];
      unset($form['custom_search_criteria_or']);
    }
    if (isset($form['custom_search_criteria_phrase'])) {
      $form['advanced_search']['custom_search_criteria_phrase'] = $form['custom_search_criteria_phrase'];
      unset($form['custom_search_criteria_phrase']);
    }
    if (isset($form['custom_search_criteria_negative'])) {
      $form['advanced_search']['custom_search_criteria_negative'] = $form['custom_search_criteria_negative'];
      unset($form['custom_search_criteria_negative']);
    }
    if (isset($form['custom_search_types'])) {
      $form['advanced_search']['custom_search_types'] = $form['custom_search_types'];
      unset($form['custom_search_types']);
    }
    if (isset($form['advanced_search']['custom_search_types']['#options']['c-classified'])){
      $form['advanced_search']['custom_search_types']['#options']['c-classified'] = 'Classified ad';
      $form['advanced_search']['custom_search_types']['#options']['c-forum'] = 'Forum topic';
      $form['advanced_search']['custom_search_types']['#options']['c-section_page'] = 'Page';
      $form['advanced_search']['custom_search_types']['#options']['c-question'] = 'Q & A';
    }
  }
}

/*
 * Implementation of hook_preprocess_search_result()
 *
 * Combine a few content types and call them "Information Pages"
 */
function atwork_search_preprocess_search_result(&$variables) {
  if (!isset($variables['result']['type'])) {
    return;
  }
  if (in_array($variables['result']['type'], array('Background', 'Section', 'Section Background'))) {
    $variables['result']['type'] = t('Information Page');
  }


  $date = format_date($variables['result']['node']->created, 'medium');

  $variables['info'] = $variables['result']['type'] . ' - ' . $variables['info_split']['user'] . ' - ' . $date;

  if (isset($variables['info_split']['comment']) && $variables['info_split']['comment']) {
    $variables['info'] .= ' - ' . $variables['info_split']['comment'];
  }
}

/*
 * Implementation of hook_ranking()
 *
 * Boost the ranking of the page content type
 */
function atwork_search_ranking() {
  return array(
    'page_boost_search' => array(
      'title' => t('Background Page Boost'),
      'arguments' => array(':page_boost' => 'page'),
      'score' => ' FIND_IN_SET(n.type, :page_boost)',
    ),
  );
}
