<?php

/**
 * @file
 * Allow users to subscribe to content posted to an organic group.
 */

/**
 * Implements hook_permission().
 */
function subscriptions_og_permission() {
  return array(
    'og subscribe' => array(
      'title' => t('Subscribe to notifications for Organic Groups'),
      'description' => t('Allows users to receive alerts when new content is posted to an Organic group.'),
    ),
  );
}


/**
 * Implements hook_subscriptions().
 */
function subscriptions_og_subscriptions($op, $arg0 = NULL, $arg1 = NULL, $arg2 = NULL) {
  switch ($op) {
    case 'types':
      $types['og'] = array(
        'title' => 'Groups',
        'access' => 'og subscribe',
        'permission' => array(
          'title' => t('Subscribe to notifications for Organic Groups'),
        ),
        'page' => 'subscriptions_og_page',
        'fields' => array('node', 'group_audience'),
        'weight' => -10,
      );
      return $types;
    // Queue: Define parameters used by Subscriptions to query which
    // subscriptions should be sent. We search for subscriptions where the value
    // is equal to the GID of any group that the newly saved $node is posted to.
    case 'queue':
      if ($arg0['module'] == 'node') {
        $node = $arg0['node'];

        $params['node']['group_audience'] = array(
          'join' => array(
            'table' => 'og_membership',
            'alias' => 'ga',
            'on' => "s.value = ga.gid AND ga.group_type = 'node'",
          ),
          'where' => array(
            array('ga.etid', $node->nid, '='),
            array('ga.entity_type', 'node', '='),
          ),
          'groupby' => 'ga.etid',
        );
        if ($arg0['type'] == 'comment') {
          $params['node']['group_audience']['where'][] = array('s.send_comments', 1, '=');
        }
        elseif ($arg0['type'] == 'node' && $arg0['action'] == 'update') {
          $params['node']['group_audience']['where'][] = array('s.send_updates', 1, '=');
        }

        return $params;
      }
      break;
    case 'fields':
      // $arg0 is module.
      if ($arg0 == 'node' || $arg0 == 'comment') {
        return array(
          'group_audience' => array(
            'data_function' => 'subscriptions_content_data',
            'subs_mod' => 'subscriptions_og',
            'subs_type' => t('group'),
            'mailkey' => 'group-type-',
          ),
        );
      }
      break;
    case 'mailkeys':
      $mailkeys = array();
      $og_bundles = og_get_all_group_bundle();
      foreach ($og_bundles['node'] as $node_type => $node_name) {
        $mailkeys['group-type-' . $node_type] = t('Notifications for group content posted to %type groups', array('%type' => $node_name));
      }
      return $mailkeys;
    case 'mailkey_alter':
      if ($arg0 == 'group-type-') {
        $groups = og_get_entity_groups('node', $arg1);
        // We take only the first group to which this node is posted. This won't
        // be correct if this node is posted to multiple, different group types.
        if (!empty($groups) && !empty($groups['node'])) {
          $group = node_load(current($groups['node']));
          return 'group-type-' . $group->type;
        }
      }
      break;
    case 'token_types':
      if (strpos($arg0, 'group-type-') === 0) {
        return array('node', 'comment');
      }
      break;
    case 'node_options':
      // $arg1 is the current node
      $options = array();
      if (og_is_group('node', $arg1)) {
        if (user_access('og subscribe') || og_is_member('node', $arg1)) {
          $options['group_audience'][] = array(
            'name' => t('To content posted in %name', array('%name' => $arg1->title)),
            'link' => 'node/' . $arg1->nid,
            'params' => array(
              'module' => 'node',
              'field' => 'group_audience',
              'value' => $arg1->nid,
            ),
          );
        }
      }
      return $options;
  }
}

/**
 * Defines a user's overview of which groups she is subscribed to.
 *
 * @param array $form
 * @param int $uid
 *     The user's UID
 */
function subscriptions_og_page(array $form, $uid) {
  $account = user_load($uid);

  // Load all active OG subscriptions for this user
  $query = db_select('subscriptions', 's', array('fetch' => PDO::FETCH_ASSOC));
  $result = $query
    ->fields('s', array('value', 'send_interval', 'author_uid', 'send_comments', 'send_updates'))
    ->condition('s.module', 'node')
    ->condition('s.field', 'group_audience')
    ->condition('s.recipient_uid', $uid)
    ->orderBy('s.author_uid')
    ->execute();
  foreach ($result as $s) {
    $subscriptions[$s['value']][$s['author_uid']] = $s;
  }

  $form[0] = array(
    '#theme' => 'subscriptions_form_table',
  );
  $defaults = array();

  $groups = og_get_all_group('node');
  $groups = node_load_multiple($groups);
  usort($groups, '_subscriptions_og_compare_groups');

  foreach ($groups as $group) {
    // Check that the user is a member of this group
    if (!og_is_member('node', $group->nid, 'user', $account)) {
      continue;
    }

    // Add the active subscriptions.
    $group_name = check_plain($group->title);

    if (!isset($subscriptions[$group->nid][-1])) {
      // author-less item is missing -- add it here.
      $subscriptions[$group->nid][-1] = array(
        'send_interval' => _subscriptions_get_setting('send_interval', $uid),
        'send_comments' => _subscriptions_get_setting('send_comments', $uid),
        'send_updates' => _subscriptions_get_setting('send_updates', $uid),
        'author_uid' => FALSE,
      );
    }
    foreach ($subscriptions[$group->nid] as $author_uid => $subscription) {
      subscriptions_form_helper($form[0], $defaults, $author_uid, $group->nid, $group_name, $subscription);
    }
  }

  if (isset($form[0]['checkboxes'])) {
    $form[0]['defaults'] = array(
      '#type' => 'value',
      '#value' => $defaults,
    );
    subscriptions_form_column_filter($form[0], $uid);
  }
  else {
    $form = array(
      array('#markup' => t('There are no available groups to subscribe to.'))
    );
  }

  return $form;
}

/**
 * Implements hook_form_FROM_ID_alter().
 *
 * Adds checkbox to allow enable/disable autosubscriptions.
 */
function subscriptions_og_form_subscriptions_settings_form_alter(&$form, &$form_state, $form_id) {

  $form['subscriptions_og'] = array(
    '#type' => 'fieldset',
    '#title' => t('Organic Groups subscriptions'),
    '#collapsible' => TRUE,
    '#weight' => -8,
  );
  $form['subscriptions_og']['subscriptions_og_autosubscribe'] = array(
    '#type' => 'checkbox',
    '#title' => 'Automatically subscribe/unsubscribe members of an organic group',
    '#default_value' => variable_get('subscriptions_og_autosubscribe', FALSE),
    '#description' => t('Automatically subscribe or unsubscribe users as the join or leave an organic group. This will not create subscriptions for existing organic group members.'),
  );
}

/**
 * Implements hook_og_membership_insert().
 */
function subscriptions_og_og_membership_insert($og_membership) {
  $autosubscribe = variable_get('subscriptions_og_autosubscribe', FALSE);
  if ($autosubscribe && $og_membership->group_type == 'node' && $og_membership->entity_type == 'user') {
    $send_interval = _subscriptions_get_setting('send_interval', $og_membership->etid);
    $send_updates = _subscriptions_get_setting('send_updates', $og_membership->etid);
    $send_comments = _subscriptions_get_setting('send_comments', $og_membership->etid);

    subscriptions_write_subscription(
      'node',               // Module
      'group_audience',     // Field
      $og_membership->gid,  // Value
      -1,                   // Author uid
      $og_membership->etid, // Recipient
      $send_interval,       // Send interval
      $send_updates,        // Send updates
      $send_comments        // Send comments
    );
  }
}

/**
 * Implements hook_og_membership_delete().
 */
function subscriptions_og_og_membership_delete($og_membership) {
  $autosubscribe = variable_get('subscriptions_og_autosubscribe', FALSE);
  if ($autosubscribe && $og_membership->group_type == 'node' && $og_membership->entity_type == 'user') {
    subscriptions_delete(
      $og_membership->etid, // Recipient
      'node',               // Module
      'group_audience',     // Field
      $og_membership->gid   // Value
    );
  }
}

/**
 * Helper function so sort organic groups.
 *
 * Intended for use with usort() and similar functions.
 *
 * @param OgGroup $first
 * @param OgGroup $second
 *
 * @return int
 * < 0 if $first comes before $second, > 0 if $second comes before $first, and
 * 0 if they are equal in sorting order.
 */
function _subscriptions_og_compare_groups($first, $second) {
  return strcmp($first->title, $second->title);
}

/**
 * Implements hook_disable().
 *
 * Removes our queue items.
 *
 * @ingroup hooks
 */
function subscriptions_og_disable() {
  db_delete('subscriptions_queue')
  ->condition('module', 'node')
  ->condition('field', 'group_audience')
  ->execute();
}


/**
 * Implements hook_node_insert().
 * Employee news wishes to be notified on all content creations
 */
function subscriptions_og_node_insert($node) {
  // Don't need certain content types - if we hit one of those, then leave immediately.
  if(isset($node->type)){
    $type = $node->type;
    switch(TRUE){
      case($type == 'ad_space'):
      case($type == 'page'):
      case($type == 'ecard'):
      case($type == 'image'):
      case($type == 'lsa_application'):
      case($type == 'multichoice'):
      case($type == 'simplenews'):
      case($type == 'quiz'):
      case($type == 'lsa_pin_application'):
      case($type == 'status_update'):
      case($type == 'webform'):
        return;
        break;
      default:
        // Do nothing
        break;
    }
  }
  // If this node is set to send notifications anyways - no point in sending another.
  if($node->subscriptions_notify == 1){
    return;
  }
  // Fires when user first saves the node. We only want to send a notification if they publish it here - otherwise we will send a note when they update from unpublished -> published.
  if($node->status != 1 ){
    return;
  }

  // Just in case we have a content type that creates nodes with no titles.
  $subscription_body = isset($node->title) ? 'A new ' . $node->type . ' titled \'<a href="/node/' . $node->nid . '">' . '"' . $node->title . '"' ."</a>\' was created by " . $node->name . ". \n" : 'A new ' . $node->type . ' titled <a href="/node/' . $node->nid . '">' . ' Untitled ' . "</a> was created by " . $node->name . ". \n";

  // Send first 150 chars of the body field to give community manager a bit of an idea.
  if(isset($node->body['und'][0]['value']) && (strlen($node->body['und'][0]['value']) > 500)){
    $clean_text = strip_tags($node->body['und'][0]['value'], "<p> <br> <i>" );
    $subscription_body = strlen($node->body['und'][0]['value']) > 500 ? $subscription_body . " \n <p><i>" . substr($clean_text, 0, 500) . "...</i></p>" : $subscription_body . " \n <p><i>" . $clean_text . "...</i></p>";
  }
  // Cute little closing salutation:
  $subscription_body = $subscription_body . " <br> <br> Love, <br> Employee News and Drupal. ";
  // admin email
  $params = [
    'subject' => 'New ' . $node->type . ' published',
    'body' => $subscription_body,
  ];
  drupal_mail('atwork_mail', 'atwork_mail_default', 'EmployeeNews@gov.bc.ca', language_default(), $params, variable_get('site_mail', 'EmployeeNews@gov.bc.ca'));
}


/**
 * Implements hook_node_update().
 * Employee news wants to be notified whenever a node is published on the site.
 */
function subscriptions_og_node_update($node) {
  // Don't need certain content types - if we hit one of those, then leave immediately.
  if(isset($node->type)){
    $type = $node->type;
    switch(TRUE){
      case($type == 'ad_space'):
      case($type == 'page'):
      case($type == 'ecard'):
      case($type == 'image'):
      case($type == 'lsa_application'):
      case($type == 'multichoice'):
      case($type == 'simplenews'):
      case($type == 'quiz'):
      case($type == 'lsa_pin_application'):
      case($type == 'status_update'):
      case($type == 'webform'):
        return;
        break;
      default:
        // Do nothing
        break;
    }
  }
  // If this node is set to send notifications anyways - no point in sending another.
  if($node->subscriptions_notify == 1){
    return;
  }
  // Fires when user first saves the node. We only want to send a notification if they publish it here from an unpublished state- otherwise we will send a note when they update from unpublished -> published.
  if($node->status != 1 && $node->original->status != 0){
    return;
  }

  // Just in case we have a content type that creates nodes with no titles.
  $subscription_body = isset($node->title) ? 'A new ' . $node->type . ' titled <a href="/node/' . $node->nid . '">' . '"' . $node->title . '"' . "</a> was created by " . $node->name . ". \n" : 'A new ' . $node->type . ' titled <a href="/node/' . $node->nid . '">' . ' Untitled ' . "</a> was created by " . $node->name . ". \n";

  // Send first 150 chars of the body field to give community manager a bit of an idea.
  $clean_text = strip_tags($node->body['und'][0]['value'], "<p> <br> <i>" );

  $subscription_body = strlen($node->body['und'][0]['value']) > 500 ? $subscription_body . " \n <p><i>" . substr($clean_text, 0, 500) . "...</i></p>" : $subscription_body . " \n <p><i>" . $clean_text . "...</i></p>";

  // Cute little closing salutation:
  $subscription_body = $subscription_body . " <br> <br> Love, <br> Employee News and Drupal. ";
  // admin email
  $params = [
    'subject' => 'New ' . $node->type . ' published',
    'body' => $subscription_body,
  ];
  drupal_mail('atwork_mail', 'atwork_mail_default', 'EmployeeNews@gov.bc.ca', language_default(), $params, variable_get('site_mail', 'EmployeeNews@gov.bc.ca'));
}
